package main

import (
	"crypto/sha1"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"hash"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

const (
	versionManifestURL = "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json"
	paperFillURL       = "https://fill.papermc.io/v3"
)

var httpClient = &http.Client{Timeout: 10 * time.Minute}

// Resolves and downloads scenario jar through cache
func serverJar(scn Scenario, cacheDir string) (string, error) {
	switch scn.Type {
	case TypeVanilla:
		return vanillaJar(scn.MCVersion, cacheDir)
	case TypePaper:
		return paperJar(scn.MCVersion, cacheDir)
	}
	return "", fmt.Errorf("unknown scenario type %q", scn.Type)
}

func vanillaJar(mcVersion, cacheDir string) (string, error) {
	var manifest struct {
		Versions []struct {
			ID  string `json:"id"`
			URL string `json:"url"`
		} `json:"versions"`
	}
	if err := getJSON(versionManifestURL, &manifest); err != nil {
		return "", err
	}
	metaURL := ""
	for _, v := range manifest.Versions {
		if v.ID == mcVersion {
			metaURL = v.URL
			break
		}
	}
	if metaURL == "" {
		return "", fmt.Errorf("MC version %s not in Mojang manifest", mcVersion)
	}
	var meta struct {
		Downloads struct {
			Server struct {
				URL  string `json:"url"`
				SHA1 string `json:"sha1"`
			} `json:"server"`
		} `json:"downloads"`
	}
	if err := getJSON(metaURL, &meta); err != nil {
		return "", err
	}
	if meta.Downloads.Server.URL == "" {
		return "", fmt.Errorf("no server jar published for MC %s", mcVersion)
	}
	return cachedDownload(meta.Downloads.Server.URL, "sha1", meta.Downloads.Server.SHA1, cacheDir)
}

func paperJar(mcVersion, cacheDir string) (string, error) {
	var build struct {
		ID        int `json:"id"`
		Downloads map[string]struct {
			URL       string `json:"url"`
			Checksums struct {
				SHA256 string `json:"sha256"`
			} `json:"checksums"`
		} `json:"downloads"`
	}
	url := fmt.Sprintf("%s/projects/paper/versions/%s/builds/latest", paperFillURL, mcVersion)
	if err := getJSON(url, &build); err != nil {
		return "", err
	}
	dl, ok := build.Downloads["server:default"]
	if !ok {
		return "", fmt.Errorf("paper build %d has no server download", build.ID)
	}
	return cachedDownload(dl.URL, "sha256", dl.Checksums.SHA256, cacheDir)
}

// Keeps one copy per checksum, skips refetching
func cachedDownload(url, algo, sum string, cacheDir string) (string, error) {
	if sum == "" {
		return "", fmt.Errorf("refusing uncheckedsummed download %s", url)
	}
	dest := filepath.Join(cacheDir, sum+".jar")
	if _, err := os.Stat(dest); err == nil {
		return dest, nil
	}
	if err := os.MkdirAll(cacheDir, 0755); err != nil {
		return "", err
	}
	resp, err := httpClient.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	tmp, err := os.CreateTemp(cacheDir, "dl-*")
	if err != nil {
		return "", err
	}
	defer os.Remove(tmp.Name())

	var h hash.Hash
	if algo == "sha1" {
		h = sha1.New()
	} else {
		h = sha256.New()
	}
	if _, err := io.Copy(io.MultiWriter(tmp, h), resp.Body); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if got := hex.EncodeToString(h.Sum(nil)); !strings.EqualFold(got, sum) {
		return "", fmt.Errorf("checksum mismatch for %s: got %s want %s", url, got, sum)
	}
	return dest, os.Rename(tmp.Name(), dest)
}

func getJSON(url string, out any) error {
	resp, err := httpClient.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("GET %s: %s", url, resp.Status)
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// Same properties for every contender in a scenario
func serverProperties(cfg *Config) string {
	props := map[string]string{
		"server-port":          "25565",
		"online-mode":          "false",
		"allow-flight":         "true",
		"level-seed":           cfg.Seed,
		"view-distance":        fmt.Sprintf("%d", cfg.ViewDistance),
		"simulation-distance":  fmt.Sprintf("%d", cfg.SimDistance),
		"max-players":          "500",
		"motd":                 "discobench",
		"enable-rcon":          "false",
		"spawn-protection":     "0",
		"sync-chunk-writes":    "false",
		"network-compression-threshold": "256",
	}
	var b strings.Builder
	b.WriteString("# generated by discobench, identical across contenders\n")
	for k, v := range props {
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	return b.String()
}

// Builds preprovisioned data dir the runtime expects
func prepareDiscopanel(cfg *Config, scn Scenario, dataDir, jarPath string) error {
	if err := os.MkdirAll(filepath.Join(dataDir, ".discopanel"), 0755); err != nil {
		return err
	}
	if err := copyFile(jarPath, filepath.Join(dataDir, "server.jar")); err != nil {
		return err
	}
	launch := map[string]any{
		"version":    1,
		"kind":       "jar",
		"jar":        "server.jar",
		"loader":     scn.Type,
		"mc_version": scn.MCVersion,
		"java_major": scn.JavaMajor,
	}
	data, err := json.MarshalIndent(launch, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dataDir, ".discopanel", "launch.json"), data, 0644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dataDir, "eula.txt"), []byte("eula=true\n"), 0644); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dataDir, "server.properties"), []byte(serverProperties(cfg)), 0644)
}

// Builds runtime image env for a bench run
func discopanelEnv(cfg *Config, extra map[string]string) []string {
	env := []string{
		fmt.Sprintf("MEMORY=%dM", cfg.HeapMB),
		"USE_AIKAR_FLAGS=true",
	}
	for k, v := range extra {
		env = append(env, k+"="+v)
	}
	return env
}

// Builds itzg env pinned to discopanel's settings
func itzgEnv(cfg *Config, scn Scenario, extra map[string]string) []string {
	serverType := "VANILLA"
	if scn.Type == TypePaper {
		serverType = "PAPER"
	}
	env := []string{
		"EULA=TRUE",
		"TYPE=" + serverType,
		"VERSION=" + scn.MCVersion,
		fmt.Sprintf("MEMORY=%dM", cfg.HeapMB),
		"USE_AIKAR_FLAGS=true",
		"ONLINE_MODE=FALSE",
		"ALLOW_FLIGHT=TRUE",
		"SEED=" + cfg.Seed,
		fmt.Sprintf("VIEW_DISTANCE=%d", cfg.ViewDistance),
		fmt.Sprintf("SIMULATION_DISTANCE=%d", cfg.SimDistance),
		"MAX_PLAYERS=500",
		"MOTD=discobench",
		"ENABLE_RCON=false",
		"SPAWN_PROTECTION=0",
		"SYNC_CHUNK_WRITES=false",
		"NETWORK_COMPRESSION_THRESHOLD=256",
		"ENABLE_AUTOPAUSE=FALSE",
		"SETUP_ONLY=false",
	}
	for k, v := range extra {
		env = append(env, k+"="+v)
	}
	return env
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}
