package provisioner

import "strings"

// Known client slugs seeded from the itzg community list
var clientOnlySlugs = map[string]bool{
	"advancement-plaques":                 true,
	"ambience-music-mod":                  true,
	"ambientsounds":                       true,
	"appleskin":                           true,
	"armor-chroma":                        true,
	"armor-toughness-bar":                 true,
	"audio-extension-for-fancymenu-forge": true,
	"auudio-forge":                        true,
	"beehivetooltips":                     true,
	"better-advancements":                 true,
	"better-foliage":                      true,
	"better-modlist-neoforge":             true,
	"better-placement":                    true,
	"better-sprinting":                    true,
	"better-third-person":                 true,
	"better-tips-nbt-tag":                 true,
	"betterf3":                            true,
	"betterfps":                           true,
	"bettergrassify":                      true,
	"biomeinfo":                           true,
	"block-drops-jei-addon":               true,
	"blur-forge":                          true,
	"cartography":                         true,
	"chattoggle":                          true,
	"cherished-worlds":                    true,
	"chunk-animator":                      true,
	"clickable-advancements":              true,
	"colorwheel":                          true,
	"colorwheel-patcher":                  true,
	"compass-coords":                      true,
	"config-menus-forge":                  true,
	"configured":                          true,
	"controllable":                        true,
	"controlling":                         true,
	"craftpresence":                       true,
	"crash-assistant":                     true,
	"ctm":                                 true,
	"cull-less-leaves":                    true,
	"custom-main-menu":                    true,
	"dark-mode-everywhere":                true,
	"defensive-measures":                  true,
	"ding":                                true,
	"distraction-free-recipes":            true,
	"drippy-loading-screen":               true,
	"dynamic-surroundings":                true,
	"dynamic-view":                        true,
	"dynamiclights-reforged":              true,
	"easiervillagertrading":               true,
	"effective-forge":                     true,
	"embeddium":                           true,
	"embeddium-extension":                 true,
	"embeddium-extras":                    true,
	"enchantment-descriptions":            true,
	"enhanced-boss-bars":                  true,
	"enhancedvisuals":                     true,
	"entity-collision-fps-fix":            true,
	"entity-model-features":               true,
	"entity-texture-features-fabric":      true,
	"entityculling":                       true,
	"equipment-compare":                   true,
	"essential-mod":                       true,
	"euphoria-patches":                    true,
	"extreme-sound-muffler":               true,
	"ezzoom":                              true,
	"fading-night-vision":                 true,
	"falling-leaves-forge":                true,
	"fancymenu":                           true,
	"farsight":                            true,
	"faster-ladder-climbing":              true,
	"fastquit":                            true,
	"fastquit-forge":                      true,
	"flerovium":                           true,
	"foamfix-optimization-mod":            true,
	"forgeskyboxes":                       true,
	"fps-reducer":                         true,
	"free-cam":                            true,
	"ftb-backups-2":                       true,
	"fullscreen-windowed-borderless-for-minecraft": true,
	"hwyla":                            true,
	"iceberg":                          true,
	"ignitioncoil":                     true,
	"illager-raid-music":               true,
	"immersive-damage-indicators":      true,
	"inmisaddon":                       true,
	"iris-flywheel-compat":             true,
	"iris-shader-folder":               true,
	"irisshaders":                      true,
	"item-borders":                     true,
	"item-highlighter":                 true,
	"item-obliterator":                 true,
	"itemphysic-lite":                  true,
	"itemzoom":                         true,
	"just-enough-harvestcraft":         true,
	"just-enough-mekanism-multiblocks": true,
	"just-enough-resources-jer":        true,
	"just-zoom":                        true,
	"legendary-tooltips":               true,
	"lighty":                           true,
	"loot-capacitor-tooltips":          true,
	"loot-journal":                     true,
	"lootbeams":                        true,
	"magnesium-extras":                 true,
	"make-bubbles-pop":                 true,
	"mekalus-oculus-fork-with-fixed-mekanism-mekasuit": true,
	"menumobs":                              true,
	"minecraft-rich-presence":               true,
	"mining-speed-tooltips":                 true,
	"model-gap-fix":                         true,
	"more-overlays":                         true,
	"mouse-tweaks":                          true,
	"neat":                                  true,
	"nekos-enchanted-books":                 true,
	"neoculus":                              true,
	"no-nv-flash":                           true,
	"no-recipe-book":                        true,
	"not-enough-animations":                 true,
	"oculus":                                true,
	"ok-zoomer":                             true,
	"oldjavawarning":                        true,
	"overloaded-armor-bar":                  true,
	"packmenu":                              true,
	"packmodemenu":                          true,
	"particle-effects":                      true,
	"particle-effects-reforged":             true,
	"particle-rain":                         true,
	"particular":                            true,
	"particular-reforged":                   true,
	"reauth":                                true,
	"rebind-narrator":                       true,
	"reblured":                              true,
	"reeses-sodium-options":                 true,
	"reforgium":                             true,
	"resource-reloader":                     true,
	"rubidium":                              true,
	"rubidium-extra":                        true,
	"ryoamiclights":                         true,
	"schematica":                            true,
	"seamless-loading-screen":               true,
	"seamless-loading-screen-forge":         true,
	"searchables":                           true,
	"seasonhud":                             true,
	"shulkerboxviewer":                      true,
	"skin-layers-3d":                        true,
	"smart-hud":                             true,
	"smithing-template-viewer":              true,
	"smooth-font":                           true,
	"smooth-swapping":                       true,
	"smoothwater":                           true,
	"sodium":                                true,
	"sodium-extra":                          true,
	"sodium-extras":                         true,
	"sodium-options-api":                    true,
	"sodium-rubidium-occlusion-culling-fix": true,
	"sound":                                 true,
	"sound-filters":                         true,
	"sound-physics-remastered":              true,
	"sound-reloader":                        true,
	"status-effect-bars-reforged":           true,
	"stellar-sky":                           true,
	"swingthroughgrass":                     true,
	"textrues-embeddium-options":            true,
	"textrues-rubidium-options":             true,
	"thaumic-jei":                           true,
	"tips":                                  true,
	"toast-control":                         true,
	"torohealth-damage-indicators":          true,
	"true-darkness":                         true,
	"ungrab-mouse-mod":                      true,
	"vanillafix":                            true,
	"visuality":                             true,
	"waila-harvestability":                  true,
	"waila-stages":                          true,
	"wakes-reforged":                        true,
	"wawla":                                 true,
	"welcome-screen":                        true,
	"xaeroplus":                             true,
	"yungs-menu-tweaks":                     true,
	"zume":                                  true,
}

// Filename prefixes catch known client jars when no slug exists
var clientOnlyFilePrefixes = []string{
	"oculus-",
	"colorwheel-",
	"controllable-",
	"fastquit",
	"sodiumextras-",
	"enhanced_boss_bars-",
	"iris_shader_folder-",
	"irisflw-",
	"fancymenu_",
	"drippyloadingscreen_",
	"embeddium-",
	"rubidium-",
	"sodium-fabric",
	"skinlayers3d-",
	"entityculling-",
	"notenoughanimations-",
	"legendarytooltips-",
	"euphoriapatcher-",
	"betterf3-",
}

// Reports whether a project slug is a known client mod
func defaultClientSlug(slug string) bool {
	return clientOnlySlugs[strings.ToLower(slug)]
}

// Reports whether a file name is a known client jar
func defaultClientFile(fileName string) bool {
	name := strings.ToLower(fileName)
	for _, p := range clientOnlyFilePrefixes {
		if strings.HasPrefix(name, p) {
			return true
		}
	}
	return false
}
