// Code generated by gormgen. DO NOT EDIT.

import { AliasCategory, ModuleProtocol } from './discopanel/v1/module_pb';
import { ProxyRouteState } from './discopanel/v1/proxy_pb';
import { FindingSource, PerformanceSeverity } from './discopanel/v1/server_pb';
import { ExecutionStatus, ModLoader, ModuleEventAction, ModuleStatus, ModuleTemplateType, ScheduleType, ServerStatus, TaskStatus, TaskType, TriggeredEventType } from './discopanel/v1/storage_pb';
import { WSMessageType } from './discopanel/v1/websocket_pb';

// Display name for the enum type
export const AliasCategoryTypeLabel = "Alias Category";

// Canonical strings by value
export const AliasCategoryName: Record<AliasCategory, string> = {
	[AliasCategory.UNSPECIFIED]: "unspecified",
	[AliasCategory.SERVER]: "server",
	[AliasCategory.MODULE]: "module",
	[AliasCategory.SPECIAL]: "special",
};

// Display labels by value
export const AliasCategoryLabel: Record<AliasCategory, string> = {
	[AliasCategory.UNSPECIFIED]: "Other",
	[AliasCategory.SERVER]: "Server",
	[AliasCategory.MODULE]: "Module",
	[AliasCategory.SPECIAL]: "Special",
};

// Enum value matching a canonical name
export function aliasCategoryFromName(name: string): AliasCategory | undefined {
	for (const [k, v] of Object.entries(AliasCategoryName)) {
		if (v === name) return Number(k) as AliasCategory;
	}
	return undefined;
}

// Display name for the enum type
export const ExecutionStatusTypeLabel = "Execution Status";

// Canonical strings by value
export const ExecutionStatusName: Record<ExecutionStatus, string> = {
	[ExecutionStatus.UNSPECIFIED]: "unspecified",
	[ExecutionStatus.PENDING]: "pending",
	[ExecutionStatus.RUNNING]: "running",
	[ExecutionStatus.COMPLETED]: "completed",
	[ExecutionStatus.FAILED]: "failed",
	[ExecutionStatus.SKIPPED]: "skipped",
	[ExecutionStatus.CANCELLED]: "cancelled",
	[ExecutionStatus.TIMEOUT]: "timeout",
};

// Display labels by value
export const ExecutionStatusLabel: Record<ExecutionStatus, string> = {
	[ExecutionStatus.UNSPECIFIED]: "Unknown",
	[ExecutionStatus.PENDING]: "Pending",
	[ExecutionStatus.RUNNING]: "Running",
	[ExecutionStatus.COMPLETED]: "Completed",
	[ExecutionStatus.FAILED]: "Failed",
	[ExecutionStatus.SKIPPED]: "Skipped",
	[ExecutionStatus.CANCELLED]: "Cancelled",
	[ExecutionStatus.TIMEOUT]: "Timeout",
};

// Enum value matching a canonical name
export function executionStatusFromName(name: string): ExecutionStatus | undefined {
	for (const [k, v] of Object.entries(ExecutionStatusName)) {
		if (v === name) return Number(k) as ExecutionStatus;
	}
	return undefined;
}

// Display name for the enum type
export const FindingSourceTypeLabel = "Finding Source";

// Canonical strings by value
export const FindingSourceName: Record<FindingSource, string> = {
	[FindingSource.UNSPECIFIED]: "unspecified",
	[FindingSource.CONFIG]: "config",
	[FindingSource.TELEMETRY]: "telemetry",
	[FindingSource.CRASH_DOCTOR]: "crash_doctor",
	[FindingSource.PREFLIGHT]: "preflight",
};

// Display labels by value
export const FindingSourceLabel: Record<FindingSource, string> = {
	[FindingSource.UNSPECIFIED]: "unknown",
	[FindingSource.CONFIG]: "config",
	[FindingSource.TELEMETRY]: "telemetry",
	[FindingSource.CRASH_DOCTOR]: "crash doctor",
	[FindingSource.PREFLIGHT]: "mod check",
};

// Enum value matching a canonical name
export function findingSourceFromName(name: string): FindingSource | undefined {
	for (const [k, v] of Object.entries(FindingSourceName)) {
		if (v === name) return Number(k) as FindingSource;
	}
	return undefined;
}

// Display name for the enum type
export const ModLoaderTypeLabel = "Mod Loader";

// Canonical strings by value
export const ModLoaderName: Record<ModLoader, string> = {
	[ModLoader.UNSPECIFIED]: "unspecified",
	[ModLoader.VANILLA]: "vanilla",
	[ModLoader.FORGE]: "forge",
	[ModLoader.FABRIC]: "fabric",
	[ModLoader.QUILT]: "quilt",
	[ModLoader.PAPER]: "paper",
	[ModLoader.SPIGOT]: "spigot",
	[ModLoader.BUKKIT]: "bukkit",
	[ModLoader.PURPUR]: "purpur",
	[ModLoader.SPONGE_VANILLA]: "spongevanilla",
	[ModLoader.SPONGE_FORGE]: "spongeforge",
	[ModLoader.MOHIST]: "mohist",
	[ModLoader.CATSERVER]: "catserver",
	[ModLoader.ARCLIGHT]: "arclight",
	[ModLoader.AUTO_CURSEFORGE]: "auto_curseforge",
	[ModLoader.MODRINTH]: "modrinth",
	[ModLoader.NEOFORGE]: "neoforge",
	[ModLoader.FOLIA]: "folia",
	[ModLoader.CUSTOM]: "custom",
	[ModLoader.PUFFERFISH]: "pufferfish",
	[ModLoader.MAGMA]: "magma",
	[ModLoader.MAGMA_MAINTAINED]: "magma_maintained",
	[ModLoader.KETTING]: "ketting",
	[ModLoader.YOUER]: "youer",
	[ModLoader.BANNER]: "banner",
	[ModLoader.LIMBO]: "limbo",
	[ModLoader.NANO_LIMBO]: "nanolimbo",
	[ModLoader.CRUCIBLE]: "crucible",
	[ModLoader.GLOWSTONE]: "glowstone",
	[ModLoader.FTBA]: "ftba",
	[ModLoader.CURSEFORGE]: "curseforge",
};

// Display labels by value
export const ModLoaderLabel: Record<ModLoader, string> = {
	[ModLoader.UNSPECIFIED]: "Unknown",
	[ModLoader.VANILLA]: "Vanilla",
	[ModLoader.FORGE]: "Minecraft Forge",
	[ModLoader.FABRIC]: "Fabric",
	[ModLoader.QUILT]: "Quilt",
	[ModLoader.PAPER]: "Paper",
	[ModLoader.SPIGOT]: "Spigot",
	[ModLoader.BUKKIT]: "Bukkit",
	[ModLoader.PURPUR]: "Purpur",
	[ModLoader.SPONGE_VANILLA]: "SpongeVanilla",
	[ModLoader.SPONGE_FORGE]: "SpongeForge",
	[ModLoader.MOHIST]: "Mohist",
	[ModLoader.CATSERVER]: "Catserver",
	[ModLoader.ARCLIGHT]: "Arclight",
	[ModLoader.AUTO_CURSEFORGE]: "Auto CurseForge",
	[ModLoader.MODRINTH]: "Modrinth",
	[ModLoader.NEOFORGE]: "NeoForge",
	[ModLoader.FOLIA]: "Folia",
	[ModLoader.CUSTOM]: "Custom",
	[ModLoader.PUFFERFISH]: "Pufferfish",
	[ModLoader.MAGMA]: "Magma",
	[ModLoader.MAGMA_MAINTAINED]: "Magma Maintained",
	[ModLoader.KETTING]: "Ketting",
	[ModLoader.YOUER]: "Youer",
	[ModLoader.BANNER]: "Banner",
	[ModLoader.LIMBO]: "Limbo",
	[ModLoader.NANO_LIMBO]: "NanoLimbo",
	[ModLoader.CRUCIBLE]: "Crucible",
	[ModLoader.GLOWSTONE]: "Glowstone",
	[ModLoader.FTBA]: "Feed The Beast",
	[ModLoader.CURSEFORGE]: "CurseForge",
};

// Longer help text by value
export const ModLoaderDesc: Partial<Record<ModLoader, string>> = {
	[ModLoader.VANILLA]: "Vanilla Minecraft server without mod support",
	[ModLoader.FORGE]: "The original and most widely used modding platform",
	[ModLoader.FABRIC]: "Lightweight and fast modding platform",
	[ModLoader.QUILT]: "Fork of Fabric with additional features",
	[ModLoader.PAPER]: "Performance-optimized fork of Spigot",
	[ModLoader.SPIGOT]: "High-performance fork of Bukkit",
	[ModLoader.BUKKIT]: "The original plugin API for Minecraft servers",
	[ModLoader.PURPUR]: "Fork of Paper with additional gameplay features",
	[ModLoader.SPONGE_VANILLA]: "Plugin platform with advanced API",
	[ModLoader.SPONGE_FORGE]: "Sponge plugin platform on top of Forge",
	[ModLoader.MOHIST]: "Hybrid server combining Forge and Paper",
	[ModLoader.CATSERVER]: "Hybrid server implementation",
	[ModLoader.ARCLIGHT]: "Modern hybrid implementation for Forge, NeoForge, and Fabric",
	[ModLoader.AUTO_CURSEFORGE]: "Automatic CurseForge modpack installer",
	[ModLoader.MODRINTH]: "Modern open-source modpack platform",
	[ModLoader.NEOFORGE]: "Modern fork of Forge with improved features",
	[ModLoader.FOLIA]: "Regionized multithreaded fork of Paper",
	[ModLoader.CUSTOM]: "Custom server implementation",
	[ModLoader.PUFFERFISH]: "Performance-focused fork of Paper",
	[ModLoader.MAGMA]: "Hybrid server supporting both Forge mods and Bukkit plugins",
	[ModLoader.MAGMA_MAINTAINED]: "Maintained fork of Magma hybrid server",
	[ModLoader.KETTING]: "Modern hybrid server for Forge and Bukkit",
	[ModLoader.YOUER]: "NeoForge hybrid server by the Mohist team",
	[ModLoader.BANNER]: "Fabric hybrid server by the Mohist team",
	[ModLoader.LIMBO]: "Lightweight server for holding players",
	[ModLoader.NANO_LIMBO]: "Ultra-lightweight server for holding players",
	[ModLoader.CRUCIBLE]: "Legacy hybrid server implementation",
	[ModLoader.GLOWSTONE]: "Open-source Minecraft server implementation",
	[ModLoader.FTBA]: "FTB modpack platform, upload the server files yourself",
	[ModLoader.CURSEFORGE]: "Popular modpack platform",
};

// Enum value matching a canonical name
export function modLoaderFromName(name: string): ModLoader | undefined {
	for (const [k, v] of Object.entries(ModLoaderName)) {
		if (v === name) return Number(k) as ModLoader;
	}
	return undefined;
}

// Display name for the enum type
export const ModuleEventActionTypeLabel = "Event Action";

// Canonical strings by value
export const ModuleEventActionName: Record<ModuleEventAction, string> = {
	[ModuleEventAction.UNSPECIFIED]: "unspecified",
	[ModuleEventAction.START]: "start",
	[ModuleEventAction.STOP]: "stop",
	[ModuleEventAction.RESTART]: "restart",
	[ModuleEventAction.EXEC]: "exec",
	[ModuleEventAction.RCON]: "rcon",
};

// Display labels by value
export const ModuleEventActionLabel: Record<ModuleEventAction, string> = {
	[ModuleEventAction.UNSPECIFIED]: "Unknown",
	[ModuleEventAction.START]: "Start",
	[ModuleEventAction.STOP]: "Stop",
	[ModuleEventAction.RESTART]: "Restart",
	[ModuleEventAction.EXEC]: "Exec",
	[ModuleEventAction.RCON]: "RCON",
};

// Longer help text by value
export const ModuleEventActionDesc: Partial<Record<ModuleEventAction, string>> = {
	[ModuleEventAction.START]: "Start this module's container",
	[ModuleEventAction.STOP]: "Stop this module's container",
	[ModuleEventAction.RESTART]: "Restart this module's container",
	[ModuleEventAction.EXEC]: "Execute a command inside this module's container",
	[ModuleEventAction.RCON]: "Send an RCON command to the parent server",
};

// Enum value matching a canonical name
export function moduleEventActionFromName(name: string): ModuleEventAction | undefined {
	for (const [k, v] of Object.entries(ModuleEventActionName)) {
		if (v === name) return Number(k) as ModuleEventAction;
	}
	return undefined;
}

// Canonical strings by value
export const ModuleProtocolName: Record<ModuleProtocol, string> = {
	[ModuleProtocol.UNSPECIFIED]: "unspecified",
	[ModuleProtocol.TCP]: "tcp",
	[ModuleProtocol.UDP]: "udp",
	[ModuleProtocol.MINECRAFT]: "minecraft",
	[ModuleProtocol.HTTP]: "http",
};

// Display labels by value
export const ModuleProtocolLabel: Record<ModuleProtocol, string> = {
	[ModuleProtocol.UNSPECIFIED]: "unspecified",
	[ModuleProtocol.TCP]: "tcp",
	[ModuleProtocol.UDP]: "udp",
	[ModuleProtocol.MINECRAFT]: "minecraft",
	[ModuleProtocol.HTTP]: "http",
};

// Enum value matching a canonical name
export function moduleProtocolFromName(name: string): ModuleProtocol | undefined {
	for (const [k, v] of Object.entries(ModuleProtocolName)) {
		if (v === name) return Number(k) as ModuleProtocol;
	}
	return undefined;
}

// Display name for the enum type
export const ModuleStatusTypeLabel = "Module Status";

// Canonical strings by value
export const ModuleStatusName: Record<ModuleStatus, string> = {
	[ModuleStatus.UNSPECIFIED]: "unspecified",
	[ModuleStatus.STOPPED]: "stopped",
	[ModuleStatus.STARTING]: "starting",
	[ModuleStatus.RUNNING]: "running",
	[ModuleStatus.STOPPING]: "stopping",
	[ModuleStatus.ERROR]: "error",
	[ModuleStatus.CREATING]: "creating",
};

// Display labels by value
export const ModuleStatusLabel: Record<ModuleStatus, string> = {
	[ModuleStatus.UNSPECIFIED]: "Unknown",
	[ModuleStatus.STOPPED]: "Stopped",
	[ModuleStatus.STARTING]: "Starting",
	[ModuleStatus.RUNNING]: "Running",
	[ModuleStatus.STOPPING]: "Stopping",
	[ModuleStatus.ERROR]: "Error",
	[ModuleStatus.CREATING]: "Creating",
};

// Enum value matching a canonical name
export function moduleStatusFromName(name: string): ModuleStatus | undefined {
	for (const [k, v] of Object.entries(ModuleStatusName)) {
		if (v === name) return Number(k) as ModuleStatus;
	}
	return undefined;
}

// Display name for the enum type
export const ModuleTemplateTypeTypeLabel = "Template Type";

// Canonical strings by value
export const ModuleTemplateTypeName: Record<ModuleTemplateType, string> = {
	[ModuleTemplateType.UNSPECIFIED]: "unspecified",
	[ModuleTemplateType.BUILTIN]: "builtin",
	[ModuleTemplateType.CUSTOM]: "custom",
};

// Display labels by value
export const ModuleTemplateTypeLabel: Record<ModuleTemplateType, string> = {
	[ModuleTemplateType.UNSPECIFIED]: "Unknown",
	[ModuleTemplateType.BUILTIN]: "Built-in",
	[ModuleTemplateType.CUSTOM]: "Custom",
};

// Enum value matching a canonical name
export function moduleTemplateTypeFromName(name: string): ModuleTemplateType | undefined {
	for (const [k, v] of Object.entries(ModuleTemplateTypeName)) {
		if (v === name) return Number(k) as ModuleTemplateType;
	}
	return undefined;
}

// Display name for the enum type
export const PerformanceSeverityTypeLabel = "Severity";

// Canonical strings by value
export const PerformanceSeverityName: Record<PerformanceSeverity, string> = {
	[PerformanceSeverity.UNSPECIFIED]: "unspecified",
	[PerformanceSeverity.OK]: "ok",
	[PerformanceSeverity.INFO]: "info",
	[PerformanceSeverity.WARNING]: "warning",
	[PerformanceSeverity.CRITICAL]: "critical",
};

// Display labels by value
export const PerformanceSeverityLabel: Record<PerformanceSeverity, string> = {
	[PerformanceSeverity.UNSPECIFIED]: "Unknown",
	[PerformanceSeverity.OK]: "OK",
	[PerformanceSeverity.INFO]: "Info",
	[PerformanceSeverity.WARNING]: "Warning",
	[PerformanceSeverity.CRITICAL]: "Critical",
};

// Enum value matching a canonical name
export function performanceSeverityFromName(name: string): PerformanceSeverity | undefined {
	for (const [k, v] of Object.entries(PerformanceSeverityName)) {
		if (v === name) return Number(k) as PerformanceSeverity;
	}
	return undefined;
}

// Display name for the enum type
export const ProxyRouteStateTypeLabel = "Route State";

// Canonical strings by value
export const ProxyRouteStateName: Record<ProxyRouteState, string> = {
	[ProxyRouteState.UNSPECIFIED]: "unspecified",
	[ProxyRouteState.ONLINE]: "online",
	[ProxyRouteState.STARTING]: "starting",
	[ProxyRouteState.OFFLINE]: "offline",
};

// Display labels by value
export const ProxyRouteStateLabel: Record<ProxyRouteState, string> = {
	[ProxyRouteState.UNSPECIFIED]: "Unknown",
	[ProxyRouteState.ONLINE]: "Online",
	[ProxyRouteState.STARTING]: "Starting",
	[ProxyRouteState.OFFLINE]: "Offline",
};

// Enum value matching a canonical name
export function proxyRouteStateFromName(name: string): ProxyRouteState | undefined {
	for (const [k, v] of Object.entries(ProxyRouteStateName)) {
		if (v === name) return Number(k) as ProxyRouteState;
	}
	return undefined;
}

// Display name for the enum type
export const ScheduleTypeTypeLabel = "Schedule Type";

// Canonical strings by value
export const ScheduleTypeName: Record<ScheduleType, string> = {
	[ScheduleType.UNSPECIFIED]: "unspecified",
	[ScheduleType.CRON]: "cron",
	[ScheduleType.INTERVAL]: "interval",
	[ScheduleType.ONCE]: "once",
	[ScheduleType.EVENT]: "event",
};

// Display labels by value
export const ScheduleTypeLabel: Record<ScheduleType, string> = {
	[ScheduleType.UNSPECIFIED]: "Unknown",
	[ScheduleType.CRON]: "Cron expression",
	[ScheduleType.INTERVAL]: "Fixed interval",
	[ScheduleType.ONCE]: "Run once",
	[ScheduleType.EVENT]: "On event",
};

// Enum value matching a canonical name
export function scheduleTypeFromName(name: string): ScheduleType | undefined {
	for (const [k, v] of Object.entries(ScheduleTypeName)) {
		if (v === name) return Number(k) as ScheduleType;
	}
	return undefined;
}

// Display name for the enum type
export const ServerStatusTypeLabel = "Server Status";

// Canonical strings by value
export const ServerStatusName: Record<ServerStatus, string> = {
	[ServerStatus.UNSPECIFIED]: "unspecified",
	[ServerStatus.CREATING]: "creating",
	[ServerStatus.STARTING]: "starting",
	[ServerStatus.RUNNING]: "running",
	[ServerStatus.STOPPING]: "stopping",
	[ServerStatus.STOPPED]: "stopped",
	[ServerStatus.ERROR]: "error",
	[ServerStatus.UNHEALTHY]: "unhealthy",
	[ServerStatus.PROVISIONING]: "provisioning",
	[ServerStatus.PAUSED]: "paused",
};

// Display labels by value
export const ServerStatusLabel: Record<ServerStatus, string> = {
	[ServerStatus.UNSPECIFIED]: "Unknown",
	[ServerStatus.CREATING]: "Creating",
	[ServerStatus.STARTING]: "Starting",
	[ServerStatus.RUNNING]: "Running",
	[ServerStatus.STOPPING]: "Stopping",
	[ServerStatus.STOPPED]: "Stopped",
	[ServerStatus.ERROR]: "Error",
	[ServerStatus.UNHEALTHY]: "Unhealthy",
	[ServerStatus.PROVISIONING]: "Provisioning",
	[ServerStatus.PAUSED]: "Sleeping",
};

// Longer help text by value
export const ServerStatusDesc: Partial<Record<ServerStatus, string>> = {
	[ServerStatus.UNSPECIFIED]: "Status unknown",
	[ServerStatus.CREATING]: "Setting up the server container",
	[ServerStatus.STARTING]: "Booting up, hang tight",
	[ServerStatus.RUNNING]: "Online and accepting players",
	[ServerStatus.STOPPING]: "Saving the world and shutting down",
	[ServerStatus.STOPPED]: "Offline, start it to play",
	[ServerStatus.ERROR]: "Something went wrong, check the console",
	[ServerStatus.UNHEALTHY]: "Up but not responding normally",
	[ServerStatus.PROVISIONING]: "Installing server files and mods",
	[ServerStatus.PAUSED]: "Paused while idle, joins wake it up",
};

// Enum value matching a canonical name
export function serverStatusFromName(name: string): ServerStatus | undefined {
	for (const [k, v] of Object.entries(ServerStatusName)) {
		if (v === name) return Number(k) as ServerStatus;
	}
	return undefined;
}

// Display name for the enum type
export const TaskStatusTypeLabel = "Task Status";

// Canonical strings by value
export const TaskStatusName: Record<TaskStatus, string> = {
	[TaskStatus.UNSPECIFIED]: "unspecified",
	[TaskStatus.ENABLED]: "enabled",
	[TaskStatus.DISABLED]: "disabled",
	[TaskStatus.PAUSED]: "paused",
};

// Display labels by value
export const TaskStatusLabel: Record<TaskStatus, string> = {
	[TaskStatus.UNSPECIFIED]: "Unknown",
	[TaskStatus.ENABLED]: "Enabled",
	[TaskStatus.DISABLED]: "Disabled",
	[TaskStatus.PAUSED]: "Paused",
};

// Enum value matching a canonical name
export function taskStatusFromName(name: string): TaskStatus | undefined {
	for (const [k, v] of Object.entries(TaskStatusName)) {
		if (v === name) return Number(k) as TaskStatus;
	}
	return undefined;
}

// Display name for the enum type
export const TaskTypeTypeLabel = "Task Type";

// Canonical strings by value
export const TaskTypeName: Record<TaskType, string> = {
	[TaskType.UNSPECIFIED]: "unspecified",
	[TaskType.COMMAND]: "command",
	[TaskType.BACKUP]: "backup",
	[TaskType.RESTART]: "restart",
	[TaskType.START]: "start",
	[TaskType.STOP]: "stop",
	[TaskType.SCRIPT]: "script",
	[TaskType.WEBHOOK]: "webhook",
};

// Display labels by value
export const TaskTypeLabel: Record<TaskType, string> = {
	[TaskType.UNSPECIFIED]: "Unknown",
	[TaskType.COMMAND]: "Command",
	[TaskType.BACKUP]: "Backup",
	[TaskType.RESTART]: "Restart",
	[TaskType.START]: "Start",
	[TaskType.STOP]: "Stop",
	[TaskType.SCRIPT]: "Script",
	[TaskType.WEBHOOK]: "Webhook",
};

// Longer help text by value
export const TaskTypeDesc: Partial<Record<TaskType, string>> = {
	[TaskType.COMMAND]: "Execute an RCON command",
	[TaskType.BACKUP]: "Create a backup",
	[TaskType.RESTART]: "Restart the server",
	[TaskType.START]: "Start the server",
	[TaskType.STOP]: "Stop the server",
	[TaskType.SCRIPT]: "Run a custom script",
	[TaskType.WEBHOOK]: "Send an HTTP webhook",
};

// Enum value matching a canonical name
export function taskTypeFromName(name: string): TaskType | undefined {
	for (const [k, v] of Object.entries(TaskTypeName)) {
		if (v === name) return Number(k) as TaskType;
	}
	return undefined;
}

// Display name for the enum type
export const TriggeredEventTypeTypeLabel = "Server Event";

// Canonical strings by value
export const TriggeredEventTypeName: Record<TriggeredEventType, string> = {
	[TriggeredEventType.UNSPECIFIED]: "unspecified",
	[TriggeredEventType.SERVER_START]: "server_start",
	[TriggeredEventType.SERVER_STOP]: "server_stop",
	[TriggeredEventType.SERVER_HEALTHY]: "server_healthy",
	[TriggeredEventType.PLAYER_JOIN]: "player_join",
	[TriggeredEventType.PLAYER_LEAVE]: "player_leave",
	[TriggeredEventType.SERVER_RESTART]: "server_restart",
	[TriggeredEventType.PLAYER_DEATH]: "player_death",
	[TriggeredEventType.PLAYER_ADVANCEMENT]: "player_advancement",
	[TriggeredEventType.PLAYER_CHAT]: "player_chat",
};

// Display labels by value
export const TriggeredEventTypeLabel: Record<TriggeredEventType, string> = {
	[TriggeredEventType.UNSPECIFIED]: "Unknown",
	[TriggeredEventType.SERVER_START]: "Server Start",
	[TriggeredEventType.SERVER_STOP]: "Server Stop",
	[TriggeredEventType.SERVER_HEALTHY]: "Server Healthy",
	[TriggeredEventType.PLAYER_JOIN]: "Player Join",
	[TriggeredEventType.PLAYER_LEAVE]: "Player Leave",
	[TriggeredEventType.SERVER_RESTART]: "Server Restart",
	[TriggeredEventType.PLAYER_DEATH]: "Player Death",
	[TriggeredEventType.PLAYER_ADVANCEMENT]: "Player Advancement",
	[TriggeredEventType.PLAYER_CHAT]: "Player Chat",
};

// Longer help text by value
export const TriggeredEventTypeDesc: Partial<Record<TriggeredEventType, string>> = {
	[TriggeredEventType.SERVER_START]: "When the server starts",
	[TriggeredEventType.SERVER_STOP]: "When the server stops",
	[TriggeredEventType.SERVER_HEALTHY]: "When the server passes its health check",
	[TriggeredEventType.PLAYER_JOIN]: "When a player joins (the player name is available as {{.player}})",
	[TriggeredEventType.PLAYER_LEAVE]: "When a player leaves (the player name is available as {{.player}})",
	[TriggeredEventType.SERVER_RESTART]: "When the server restarts",
	[TriggeredEventType.PLAYER_DEATH]: "When a player dies ({{.player}}, death message as {{.detail}})",
	[TriggeredEventType.PLAYER_ADVANCEMENT]: "When a player earns an advancement ({{.player}}, advancement as {{.detail}})",
	[TriggeredEventType.PLAYER_CHAT]: "When a player chats ({{.player}}, message as {{.detail}})",
};

// Enum value matching a canonical name
export function triggeredEventTypeFromName(name: string): TriggeredEventType | undefined {
	for (const [k, v] of Object.entries(TriggeredEventTypeName)) {
		if (v === name) return Number(k) as TriggeredEventType;
	}
	return undefined;
}

// Canonical strings by value
export const WSMessageTypeName: Record<WSMessageType, string> = {
	[WSMessageType.WS_MESSAGE_TYPE_UNSPECIFIED]: "ws_message_type_unspecified",
	[WSMessageType.WS_MESSAGE_TYPE_AUTH]: "ws_message_type_auth",
	[WSMessageType.WS_MESSAGE_TYPE_SUBSCRIBE]: "ws_message_type_subscribe",
	[WSMessageType.WS_MESSAGE_TYPE_UNSUBSCRIBE]: "ws_message_type_unsubscribe",
	[WSMessageType.WS_MESSAGE_TYPE_COMMAND]: "ws_message_type_command",
	[WSMessageType.WS_MESSAGE_TYPE_PING]: "ws_message_type_ping",
	[WSMessageType.WS_MESSAGE_TYPE_AUTH_OK]: "ws_message_type_auth_ok",
	[WSMessageType.WS_MESSAGE_TYPE_AUTH_FAIL]: "ws_message_type_auth_fail",
	[WSMessageType.WS_MESSAGE_TYPE_SUBSCRIBED]: "ws_message_type_subscribed",
	[WSMessageType.WS_MESSAGE_TYPE_UNSUBSCRIBED]: "ws_message_type_unsubscribed",
	[WSMessageType.WS_MESSAGE_TYPE_LOGS]: "ws_message_type_logs",
	[WSMessageType.WS_MESSAGE_TYPE_LOG]: "ws_message_type_log",
	[WSMessageType.WS_MESSAGE_TYPE_COMMAND_RESULT]: "ws_message_type_command_result",
	[WSMessageType.WS_MESSAGE_TYPE_ERROR]: "ws_message_type_error",
	[WSMessageType.WS_MESSAGE_TYPE_PONG]: "ws_message_type_pong",
	[WSMessageType.WS_MESSAGE_TYPE_METRICS]: "ws_message_type_metrics",
};

// Display labels by value
export const WSMessageTypeLabel: Record<WSMessageType, string> = {
	[WSMessageType.WS_MESSAGE_TYPE_UNSPECIFIED]: "ws_message_type_unspecified",
	[WSMessageType.WS_MESSAGE_TYPE_AUTH]: "ws_message_type_auth",
	[WSMessageType.WS_MESSAGE_TYPE_SUBSCRIBE]: "ws_message_type_subscribe",
	[WSMessageType.WS_MESSAGE_TYPE_UNSUBSCRIBE]: "ws_message_type_unsubscribe",
	[WSMessageType.WS_MESSAGE_TYPE_COMMAND]: "ws_message_type_command",
	[WSMessageType.WS_MESSAGE_TYPE_PING]: "ws_message_type_ping",
	[WSMessageType.WS_MESSAGE_TYPE_AUTH_OK]: "ws_message_type_auth_ok",
	[WSMessageType.WS_MESSAGE_TYPE_AUTH_FAIL]: "ws_message_type_auth_fail",
	[WSMessageType.WS_MESSAGE_TYPE_SUBSCRIBED]: "ws_message_type_subscribed",
	[WSMessageType.WS_MESSAGE_TYPE_UNSUBSCRIBED]: "ws_message_type_unsubscribed",
	[WSMessageType.WS_MESSAGE_TYPE_LOGS]: "ws_message_type_logs",
	[WSMessageType.WS_MESSAGE_TYPE_LOG]: "ws_message_type_log",
	[WSMessageType.WS_MESSAGE_TYPE_COMMAND_RESULT]: "ws_message_type_command_result",
	[WSMessageType.WS_MESSAGE_TYPE_ERROR]: "ws_message_type_error",
	[WSMessageType.WS_MESSAGE_TYPE_PONG]: "ws_message_type_pong",
	[WSMessageType.WS_MESSAGE_TYPE_METRICS]: "ws_message_type_metrics",
};

// Enum value matching a canonical name
export function wSMessageTypeFromName(name: string): WSMessageType | undefined {
	for (const [k, v] of Object.entries(WSMessageTypeName)) {
		if (v === name) return Number(k) as WSMessageType;
	}
	return undefined;
}
