// Block definitions with colors for rendering
// Colors are approximate RGB values based on Minecraft block textures

export interface BlockDefinition {
  name: string;
  color: number; // RGB hex color
  transparent: boolean;
  emissive: boolean;
  lightLevel: number;
  solid: boolean;
}

// Common Minecraft blocks with their approximate colors
export const BLOCK_COLORS: Record<string, BlockDefinition> = {
  'minecraft:air': { name: 'Air', color: 0x000000, transparent: true, emissive: false, lightLevel: 0, solid: false },
  'minecraft:stone': { name: 'Stone', color: 0x7d7d7d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:granite': { name: 'Granite', color: 0x9a6c5b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:polished_granite': { name: 'Polished Granite', color: 0xa07a69, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:diorite': { name: 'Diorite', color: 0xbcbcbc, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:polished_diorite': { name: 'Polished Diorite', color: 0xc9c9c9, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:andesite': { name: 'Andesite', color: 0x888888, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:polished_andesite': { name: 'Polished Andesite', color: 0x9a9a9a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:grass_block': { name: 'Grass Block', color: 0x5d9b47, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dirt': { name: 'Dirt', color: 0x86653a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:coarse_dirt': { name: 'Coarse Dirt', color: 0x77593b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:podzol': { name: 'Podzol', color: 0x5c3d1d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:cobblestone': { name: 'Cobblestone', color: 0x7a7a7a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:oak_planks': { name: 'Oak Planks', color: 0xb08b4f, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:spruce_planks': { name: 'Spruce Planks', color: 0x6b4d2e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:birch_planks': { name: 'Birch Planks', color: 0xc5b77c, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:jungle_planks': { name: 'Jungle Planks', color: 0xa47650, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:acacia_planks': { name: 'Acacia Planks', color: 0xa85c32, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dark_oak_planks': { name: 'Dark Oak Planks', color: 0x422a14, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:mangrove_planks': { name: 'Mangrove Planks', color: 0x773838, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:cherry_planks': { name: 'Cherry Planks', color: 0xe7c4c4, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:bamboo_planks': { name: 'Bamboo Planks', color: 0xc4b264, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:bedrock': { name: 'Bedrock', color: 0x535353, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:water': { name: 'Water', color: 0x3f76e4, transparent: true, emissive: false, lightLevel: 0, solid: false },
  'minecraft:lava': { name: 'Lava', color: 0xd45a12, transparent: false, emissive: true, lightLevel: 15, solid: false },
  'minecraft:sand': { name: 'Sand', color: 0xd9cf9e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:red_sand': { name: 'Red Sand', color: 0xa85422, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:gravel': { name: 'Gravel', color: 0x837f7e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:gold_ore': { name: 'Gold Ore', color: 0x8b8b7a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_gold_ore': { name: 'Deepslate Gold Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:iron_ore': { name: 'Iron Ore', color: 0x8a8279, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_iron_ore': { name: 'Deepslate Iron Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:coal_ore': { name: 'Coal Ore', color: 0x747474, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_coal_ore': { name: 'Deepslate Coal Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:oak_log': { name: 'Oak Log', color: 0x6b5439, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:spruce_log': { name: 'Spruce Log', color: 0x3b2713, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:birch_log': { name: 'Birch Log', color: 0xd5ceaf, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:jungle_log': { name: 'Jungle Log', color: 0x564821, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:acacia_log': { name: 'Acacia Log', color: 0x676157, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dark_oak_log': { name: 'Dark Oak Log', color: 0x3e2912, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:oak_leaves': { name: 'Oak Leaves', color: 0x48b518, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:spruce_leaves': { name: 'Spruce Leaves', color: 0x3d6528, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:birch_leaves': { name: 'Birch Leaves', color: 0x6a9441, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:jungle_leaves': { name: 'Jungle Leaves', color: 0x37a22e, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:acacia_leaves': { name: 'Acacia Leaves', color: 0x58a521, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dark_oak_leaves': { name: 'Dark Oak Leaves', color: 0x3d6528, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:sponge': { name: 'Sponge', color: 0xc2b939, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:glass': { name: 'Glass', color: 0xd9f1f7, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:lapis_ore': { name: 'Lapis Ore', color: 0x6b7a8c, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:lapis_block': { name: 'Lapis Block', color: 0x1e4c9a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dispenser': { name: 'Dispenser', color: 0x8b8b8b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:sandstone': { name: 'Sandstone', color: 0xd8cd9f, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:note_block': { name: 'Note Block', color: 0x6b4d2e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:white_wool': { name: 'White Wool', color: 0xeaeaea, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:orange_wool': { name: 'Orange Wool', color: 0xea7e35, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:magenta_wool': { name: 'Magenta Wool', color: 0xbe49c9, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:light_blue_wool': { name: 'Light Blue Wool', color: 0x6387d2, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:yellow_wool': { name: 'Yellow Wool', color: 0xc2b51c, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:lime_wool': { name: 'Lime Wool', color: 0x39ba2e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:pink_wool': { name: 'Pink Wool', color: 0xd98199, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:gray_wool': { name: 'Gray Wool', color: 0x414141, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:light_gray_wool': { name: 'Light Gray Wool', color: 0x9c9c94, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:cyan_wool': { name: 'Cyan Wool', color: 0x287697, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:purple_wool': { name: 'Purple Wool', color: 0x7b2fbe, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:blue_wool': { name: 'Blue Wool', color: 0x35399d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:brown_wool': { name: 'Brown Wool', color: 0x724728, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:green_wool': { name: 'Green Wool', color: 0x546d1b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:red_wool': { name: 'Red Wool', color: 0xa12722, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:black_wool': { name: 'Black Wool', color: 0x1a1a1a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:gold_block': { name: 'Gold Block', color: 0xf6d03f, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:iron_block': { name: 'Iron Block', color: 0xdbdbdb, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:bricks': { name: 'Bricks', color: 0x966464, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:tnt': { name: 'TNT', color: 0xdb4e37, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:bookshelf': { name: 'Bookshelf', color: 0x6b4d2e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:mossy_cobblestone': { name: 'Mossy Cobblestone', color: 0x6b7d54, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:obsidian': { name: 'Obsidian', color: 0x14101d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:torch': { name: 'Torch', color: 0xffcc33, transparent: true, emissive: true, lightLevel: 14, solid: false },
  'minecraft:spawner': { name: 'Spawner', color: 0x1a2030, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:chest': { name: 'Chest', color: 0x9f7d39, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:diamond_ore': { name: 'Diamond Ore', color: 0x7d9e9e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_diamond_ore': { name: 'Deepslate Diamond Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:diamond_block': { name: 'Diamond Block', color: 0x61dbd5, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:crafting_table': { name: 'Crafting Table', color: 0x9f7d39, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:furnace': { name: 'Furnace', color: 0x8b8b8b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:ladder': { name: 'Ladder', color: 0x9f7d39, transparent: true, emissive: false, lightLevel: 0, solid: false },
  'minecraft:rail': { name: 'Rail', color: 0x9f7d39, transparent: true, emissive: false, lightLevel: 0, solid: false },
  'minecraft:lever': { name: 'Lever', color: 0x8b8b8b, transparent: true, emissive: false, lightLevel: 0, solid: false },
  'minecraft:redstone_ore': { name: 'Redstone Ore', color: 0x8b4d4d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_redstone_ore': { name: 'Deepslate Redstone Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:redstone_torch': { name: 'Redstone Torch', color: 0xfd0000, transparent: true, emissive: true, lightLevel: 7, solid: false },
  'minecraft:snow': { name: 'Snow', color: 0xf0fafa, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:ice': { name: 'Ice', color: 0x8eb4e4, transparent: true, emissive: false, lightLevel: 0, solid: true },
  'minecraft:snow_block': { name: 'Snow Block', color: 0xf0fafa, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:cactus': { name: 'Cactus', color: 0x0d6318, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:clay': { name: 'Clay', color: 0xa4a8b3, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:jukebox': { name: 'Jukebox', color: 0x6b4d2e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:pumpkin': { name: 'Pumpkin', color: 0xc07615, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:netherrack': { name: 'Netherrack', color: 0x6f3634, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:soul_sand': { name: 'Soul Sand', color: 0x51413a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:glowstone': { name: 'Glowstone', color: 0xf9d49c, transparent: false, emissive: true, lightLevel: 15, solid: true },
  'minecraft:jack_o_lantern': { name: 'Jack o\'Lantern', color: 0xc07615, transparent: false, emissive: true, lightLevel: 15, solid: true },
  'minecraft:stone_bricks': { name: 'Stone Bricks', color: 0x7d7d7d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:mossy_stone_bricks': { name: 'Mossy Stone Bricks', color: 0x6b7d54, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:cracked_stone_bricks': { name: 'Cracked Stone Bricks', color: 0x7d7d7d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:chiseled_stone_bricks': { name: 'Chiseled Stone Bricks', color: 0x7d7d7d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate': { name: 'Deepslate', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:cobbled_deepslate': { name: 'Cobbled Deepslate', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:polished_deepslate': { name: 'Polished Deepslate', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_bricks': { name: 'Deepslate Bricks', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_tiles': { name: 'Deepslate Tiles', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:copper_ore': { name: 'Copper Ore', color: 0x7d7d7d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_copper_ore': { name: 'Deepslate Copper Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:copper_block': { name: 'Copper Block', color: 0xc06d4d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:exposed_copper': { name: 'Exposed Copper', color: 0xa07d64, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:weathered_copper': { name: 'Weathered Copper', color: 0x6d916d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:oxidized_copper': { name: 'Oxidized Copper', color: 0x52a07d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:amethyst_block': { name: 'Amethyst Block', color: 0x8464b4, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:tuff': { name: 'Tuff', color: 0x6d6d5a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:calcite': { name: 'Calcite', color: 0xdfdfd7, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dripstone_block': { name: 'Dripstone Block', color: 0x8b7355, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:emerald_ore': { name: 'Emerald Ore', color: 0x7d9e7d, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:deepslate_emerald_ore': { name: 'Deepslate Emerald Ore', color: 0x515151, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:emerald_block': { name: 'Emerald Block', color: 0x2dc250, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:nether_bricks': { name: 'Nether Bricks', color: 0x2d171b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:end_stone': { name: 'End Stone', color: 0xddd8a0, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:end_stone_bricks': { name: 'End Stone Bricks', color: 0xddd8a0, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:quartz_block': { name: 'Quartz Block', color: 0xece7df, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:prismarine': { name: 'Prismarine', color: 0x63ab9e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:sea_lantern': { name: 'Sea Lantern', color: 0xd8f0e8, transparent: false, emissive: true, lightLevel: 15, solid: true },
  'minecraft:terracotta': { name: 'Terracotta', color: 0x985e45, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:magma_block': { name: 'Magma Block', color: 0x8c3626, transparent: false, emissive: true, lightLevel: 3, solid: true },
  'minecraft:nether_wart_block': { name: 'Nether Wart Block', color: 0x730202, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:red_nether_bricks': { name: 'Red Nether Bricks', color: 0x450607, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:bone_block': { name: 'Bone Block', color: 0xe1ddc9, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:concrete': { name: 'Concrete', color: 0xcfd5d6, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:dried_kelp_block': { name: 'Dried Kelp Block', color: 0x374b1a, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:blackstone': { name: 'Blackstone', color: 0x2a252b, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:basalt': { name: 'Basalt', color: 0x4a4b4e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:crying_obsidian': { name: 'Crying Obsidian', color: 0x14101d, transparent: false, emissive: true, lightLevel: 10, solid: true },
  'minecraft:ancient_debris': { name: 'Ancient Debris', color: 0x5c4633, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:netherite_block': { name: 'Netherite Block', color: 0x3d3a3e, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:shroomlight': { name: 'Shroomlight', color: 0xf09840, transparent: false, emissive: true, lightLevel: 15, solid: true },
  'minecraft:warped_nylium': { name: 'Warped Nylium', color: 0x2c7164, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:crimson_nylium': { name: 'Crimson Nylium', color: 0x992626, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:sculk': { name: 'Sculk', color: 0x0d1c21, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:sculk_catalyst': { name: 'Sculk Catalyst', color: 0x0d1c21, transparent: false, emissive: true, lightLevel: 6, solid: true },
  'minecraft:mud': { name: 'Mud', color: 0x3c3837, transparent: false, emissive: false, lightLevel: 0, solid: true },
  'minecraft:mud_bricks': { name: 'Mud Bricks', color: 0x8a7669, transparent: false, emissive: false, lightLevel: 0, solid: true },
};

// Get block color, with fallback for unknown blocks
export function getBlockColor(blockName: string): number {
  const def = BLOCK_COLORS[blockName];
  if (def) return def.color;

  // Generate a deterministic color for unknown blocks
  let hash = 0;
  for (let i = 0; i < blockName.length; i++) {
    hash = ((hash << 5) - hash + blockName.charCodeAt(i)) | 0;
  }
  return Math.abs(hash) % 0xffffff;
}

// Get block definition, with fallback
export function getBlockDefinition(blockName: string): BlockDefinition {
  return BLOCK_COLORS[blockName] || {
    name: blockName.replace('minecraft:', '').replace(/_/g, ' '),
    color: getBlockColor(blockName),
    transparent: blockName.includes('air') || blockName.includes('glass') || blockName.includes('leaves'),
    emissive: blockName.includes('glow') || blockName.includes('lantern') || blockName.includes('torch'),
    lightLevel: 0,
    solid: !blockName.includes('air') && !blockName.includes('water') && !blockName.includes('lava'),
  };
}

