// Emits static enum string code for go and typescript
package main

import (
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// Renders enums.gen.go with name and label methods
func renderGoEnums(enums []*enumSpec) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by gormgen. DO NOT EDIT.\n\npackage discopanelv1\n")

	for _, e := range enums {
		if e.opts != nil && e.opts.Label != "" {
			b.WriteString(fmt.Sprintf("\n// Display name for the enum type\nfunc (%s) TypeLabel() string { return %q }\n", e.name, e.opts.Label))
		}

		b.WriteString(fmt.Sprintf("\n// Canonical string for this value\nfunc (x %s) Name() string {\n\tswitch x {\n", e.name))
		for _, v := range e.values {
			b.WriteString(fmt.Sprintf("\tcase %s:\n\t\treturn %q\n", v.goConst, v.name))
		}
		b.WriteString("\t}\n\treturn \"\"\n}\n")

		b.WriteString(fmt.Sprintf("\n// Display label for this value\nfunc (x %s) Label() string {\n\tswitch x {\n", e.name))
		for _, v := range e.values {
			b.WriteString(fmt.Sprintf("\tcase %s:\n\t\treturn %q\n", v.goConst, v.label))
		}
		b.WriteString("\t}\n\treturn \"\"\n}\n")

		if hasHelp(e) {
			b.WriteString(fmt.Sprintf("\n// Longer help text for this value\nfunc (x %s) Desc() string {\n\tswitch x {\n", e.name))
			for _, v := range e.values {
				if v.help == "" {
					continue
				}
				b.WriteString(fmt.Sprintf("\tcase %s:\n\t\treturn %q\n", v.goConst, v.help))
			}
			b.WriteString("\t}\n\treturn \"\"\n}\n")
		}

		b.WriteString(fmt.Sprintf("\n// Enum value matching a canonical name, false when unknown\nfunc %sFromName(s string) (%s, bool) {\n\tswitch s {\n", e.name, e.name))
		seen := map[string]bool{}
		for _, v := range e.values {
			if seen[v.name] {
				continue
			}
			seen[v.name] = true
			b.WriteString(fmt.Sprintf("\tcase %q:\n\t\treturn %s, true\n", v.name, v.goConst))
		}
		b.WriteString(fmt.Sprintf("\t}\n\treturn %s(0), false\n}\n", e.name))
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fatal("format enums: %v\n%s", err, b.String())
	}
	return formatted
}

// Renders enums.gen.ts with name and label maps
func renderTsEnums(enums []*enumSpec) []byte {
	var b strings.Builder
	b.WriteString("// Code generated by gormgen. DO NOT EDIT.\n\n")

	byFile := map[string][]string{}
	for _, e := range enums {
		byFile[e.file] = append(byFile[e.file], e.name)
	}
	files := make([]string, 0, len(byFile))
	for f := range byFile {
		files = append(files, f)
	}
	sort.Strings(files)
	for _, f := range files {
		names := byFile[f]
		sort.Strings(names)
		b.WriteString(fmt.Sprintf("import { %s } from './%s_pb';\n", strings.Join(names, ", "), f))
	}

	for _, e := range enums {
		if e.opts != nil && e.opts.Label != "" {
			b.WriteString(fmt.Sprintf("\n// Display name for the enum type\nexport const %sTypeLabel = %q;\n", e.name, e.opts.Label))
		}

		b.WriteString(fmt.Sprintf("\n// Canonical strings by value\nexport const %sName: Record<%s, string> = {\n", e.name, e.name))
		for _, v := range e.values {
			b.WriteString(fmt.Sprintf("\t[%s.%s]: %q,\n", e.name, v.tsName, v.name))
		}
		b.WriteString("};\n")

		b.WriteString(fmt.Sprintf("\n// Display labels by value\nexport const %sLabel: Record<%s, string> = {\n", e.name, e.name))
		for _, v := range e.values {
			b.WriteString(fmt.Sprintf("\t[%s.%s]: %q,\n", e.name, v.tsName, v.label))
		}
		b.WriteString("};\n")

		if hasHelp(e) {
			b.WriteString(fmt.Sprintf("\n// Longer help text by value\nexport const %sDesc: Partial<Record<%s, string>> = {\n", e.name, e.name))
			for _, v := range e.values {
				if v.help == "" {
					continue
				}
				b.WriteString(fmt.Sprintf("\t[%s.%s]: %q,\n", e.name, v.tsName, v.help))
			}
			b.WriteString("};\n")
		}

		fn := lowerFirst(e.name)
		b.WriteString(fmt.Sprintf("\n// Enum value matching a canonical name\nexport function %sFromName(name: string): %s | undefined {\n", fn, e.name))
		b.WriteString(fmt.Sprintf("\tfor (const [k, v] of Object.entries(%sName)) {\n\t\tif (v === name) return Number(k) as %s;\n\t}\n\treturn undefined;\n}\n", e.name, e.name))
	}

	return []byte(b.String())
}

func hasHelp(e *enumSpec) bool {
	for _, v := range e.values {
		if v.help != "" {
			return true
		}
	}
	return false
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] += 'a' - 'A'
	}
	return string(r)
}
