// Emits store crud methods from db_model annotations
package main

import (
	"fmt"
	"go/format"
	"strings"

	optionsv1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/options/v1"
	"google.golang.org/protobuf/reflect/protoreflect"
)

// One parsed query parameter
type queryParam struct {
	name string
	typ  string
}

// Renders store.gen.go with methods on Store
func renderStore(models []*modelSpec) []byte {
	var b strings.Builder
	needsTime := false
	needsUUID := false

	var body strings.Builder
	for _, m := range models {
		skip := map[string]bool{}
		for _, s := range m.opts.Skip {
			skip[s] = true
		}
		if !skip["create"] {
			if emitCreate(&body, m) {
				needsUUID = true
			}
		}
		if !skip["get"] {
			emitGet(&body, m)
		}
		if !skip["list"] {
			emitList(&body, m)
		}
		if !skip["update"] {
			emitUpdate(&body, m)
		}
		if !skip["update_fields"] {
			emitUpdateFields(&body, m)
		}
		if !skip["delete"] {
			emitDelete(&body, m)
		}
		if !skip["count"] {
			emitCount(&body, m)
		}
		if m.opts.Upsert {
			emitUpsert(&body, m)
		}
		for _, q := range m.opts.Queries {
			if emitQuery(&body, m, q) {
				needsTime = true
			}
		}
	}

	b.WriteString("// Code generated by gormgen. DO NOT EDIT.\n\npackage db\n\nimport (\n\t\"context\"\n\t\"errors\"\n\t\"fmt\"\n")
	if needsTime {
		b.WriteString("\t\"time\"\n")
	}
	b.WriteString("\n")
	if needsUUID {
		b.WriteString("\t\"github.com/google/uuid\"\n")
	}
	b.WriteString("\tv1 \"github.com/nickheyer/discopanel/pkg/proto/discopanel/v1\"\n\t\"gorm.io/gorm\"\n\t\"gorm.io/gorm/clause\"\n)\n")
	b.WriteString(body.String())

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fatal("format store: %v\n%s", err, b.String())
	}
	return formatted
}

// True when the model uses a generated uuid id
func uuidPK(m *modelSpec) bool {
	return len(m.pks) == 1 && m.pks[0].kind == protoreflect.StringKind && m.pks[0].column == "id" && !m.pks[0].autoInc
}

// Go parameter list for the primary key
func pkParams(m *modelSpec) []queryParam {
	var out []queryParam
	for _, pk := range m.pks {
		out = append(out, queryParam{name: paramName(pk.column), typ: goKind(pk.kind)})
	}
	return out
}

// Sql predicate matching the primary key
func pkWhere(m *modelSpec) string {
	var parts []string
	for _, pk := range m.pks {
		parts = append(parts, pk.column+" = ?")
	}
	return strings.Join(parts, " AND ")
}

func goKind(k protoreflect.Kind) string {
	switch k {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.FloatKind:
		return "float32"
	}
	fatal("unsupported pk kind %v", k)
	return ""
}

func sigOf(params []queryParam) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.name+" "+p.typ)
	}
	return strings.Join(parts, ", ")
}

func argsOf(params []queryParam) string {
	var parts []string
	for _, p := range params {
		parts = append(parts, p.name)
	}
	return strings.Join(parts, ", ")
}

// Parses annotation params into typed go parameters
func parseParams(specs []string) []queryParam {
	var out []queryParam
	for _, s := range specs {
		name, typ, ok := strings.Cut(strings.TrimSpace(s), " ")
		if !ok {
			fatal("bad query param %q", s)
		}
		switch typ {
		case "string", "int", "int32", "int64", "uint", "uint32", "uint64", "bool", "float32", "float64", "time.Time":
		default:
			typ = "v1." + typ
		}
		out = append(out, queryParam{name: name, typ: typ})
	}
	return out
}

func usesTime(params []queryParam) bool {
	for _, p := range params {
		if p.typ == "time.Time" {
			return true
		}
	}
	return false
}

func emitCreate(b *strings.Builder, m *modelSpec) bool {
	fmt.Fprintf(b, "\n// Inserts rows into %s\nfunc (s *Store) Create%s(ctx context.Context, rows ...*v1.%s) error {\n", m.opts.Table, m.name, m.name)
	b.WriteString("\tif len(rows) == 0 {\n\t\treturn nil\n\t}\n")
	uses := uuidPK(m)
	if uses {
		fmt.Fprintf(b, "\tfor _, r := range rows {\n\t\tif r.%s == \"\" {\n\t\t\tr.%s = uuid.New().String()\n\t\t}\n\t}\n", m.pks[0].goName, m.pks[0].goName)
	}
	b.WriteString("\treturn s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error\n}\n")
	return uses
}

func emitGet(b *strings.Builder, m *modelSpec) {
	params := pkParams(m)
	fmt.Fprintf(b, "\n// Loads one row from %s\nfunc (s *Store) Get%s(ctx context.Context, %s) (*v1.%s, error) {\n", m.opts.Table, m.name, sigOf(params), m.name)
	fmt.Fprintf(b, "\tvar row v1.%s\n", m.name)
	fmt.Fprintf(b, "\tif err := s.db.WithContext(ctx).First(&row, %q, %s).Error; err != nil {\n", pkWhere(m), argsOf(params))
	fmt.Fprintf(b, "\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn nil, fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t\t}\n\t\treturn nil, err\n\t}\n\treturn &row, nil\n}\n", humanName(m.name))
}

func emitList(b *strings.Builder, m *modelSpec) {
	fmt.Fprintf(b, "\n// Lists rows from %s\nfunc (s *Store) List%s(ctx context.Context) ([]*v1.%s, error) {\n", m.opts.Table, plural(m.name), m.name)
	fmt.Fprintf(b, "\tvar rows []*v1.%s\n", m.name)
	q := "s.db.WithContext(ctx)"
	if m.opts.OrderBy != "" {
		q += fmt.Sprintf(".Order(%q)", m.opts.OrderBy)
	}
	fmt.Fprintf(b, "\tif err := %s.Find(&rows).Error; err != nil {\n\t\treturn nil, err\n\t}\n\treturn rows, nil\n}\n", q)
}

func emitUpdate(b *strings.Builder, m *modelSpec) {
	fmt.Fprintf(b, "\n// Saves one row into %s\nfunc (s *Store) Update%s(ctx context.Context, row *v1.%s) error {\n", m.opts.Table, m.name, m.name)
	b.WriteString("\treturn s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error\n}\n")
}

func emitUpdateFields(b *strings.Builder, m *modelSpec) {
	params := pkParams(m)
	fmt.Fprintf(b, "\n// Patches columns on one %s row\nfunc (s *Store) Update%sFields(ctx context.Context, %s, fields map[string]any) error {\n", m.opts.Table, m.name, sigOf(params))
	b.WriteString("\tif len(fields) == 0 {\n\t\treturn nil\n\t}\n")
	fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).Model(&v1.%s{}).Where(%q, %s).Updates(fields)\n", m.name, pkWhere(m), argsOf(params))
	fmt.Fprintf(b, "\tif res.Error != nil {\n\t\treturn res.Error\n\t}\n\tif res.RowsAffected == 0 {\n\t\treturn fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t}\n\treturn nil\n}\n", humanName(m.name))
}

func emitDelete(b *strings.Builder, m *modelSpec) {
	params := pkParams(m)
	fmt.Fprintf(b, "\n// Deletes one row from %s\nfunc (s *Store) Delete%s(ctx context.Context, %s) error {\n", m.opts.Table, m.name, sigOf(params))

	for _, g := range m.opts.Guards {
		fmt.Fprintf(b, "\tvar refs%s int64\n", g.Model)
		fmt.Fprintf(b, "\tif err := s.db.WithContext(ctx).Model(&v1.%s{}).Where(%q, %s).Count(&refs%s).Error; err != nil {\n\t\treturn err\n\t}\n", g.Model, g.Fk+" = ?", params[0].name, g.Model)
		fmt.Fprintf(b, "\tif refs%s > 0 {\n\t\treturn fmt.Errorf(\"%s still referenced by %%d %s rows\", refs%s)\n\t}\n", g.Model, humanName(m.name), humanName(g.Model), g.Model)
	}

	if len(m.opts.Cascades) == 0 {
		fmt.Fprintf(b, "\treturn s.db.WithContext(ctx).Delete(&v1.%s{}, %q, %s).Error\n}\n", m.name, pkWhere(m), argsOf(params))
		return
	}

	needsParent := false
	for _, c := range m.opts.Cascades {
		if c.Key != "" && c.Key != m.pks[0].column {
			needsParent = true
		}
	}
	b.WriteString("\treturn s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {\n")
	if needsParent {
		fmt.Fprintf(b, "\t\tvar parent v1.%s\n", m.name)
		fmt.Fprintf(b, "\t\tif err := tx.First(&parent, %q, %s).Error; err != nil {\n\t\t\treturn err\n\t\t}\n", pkWhere(m), argsOf(params))
	}
	for _, c := range m.opts.Cascades {
		val := params[0].name
		if c.Key != "" && c.Key != m.pks[0].column {
			val = "parent." + goFieldFor(m, c.Key)
		}
		fmt.Fprintf(b, "\t\tif err := tx.Delete(&v1.%s{}, %q, %s).Error; err != nil {\n\t\t\treturn err\n\t\t}\n", c.Model, c.Fk+" = ?", val)
	}
	fmt.Fprintf(b, "\t\treturn tx.Delete(&v1.%s{}, %q, %s).Error\n\t})\n}\n", m.name, pkWhere(m), argsOf(params))
}

func emitCount(b *strings.Builder, m *modelSpec) {
	fmt.Fprintf(b, "\n// Counts rows in %s\nfunc (s *Store) Count%s(ctx context.Context) (int64, error) {\n", m.opts.Table, plural(m.name))
	fmt.Fprintf(b, "\tvar count int64\n\terr := s.db.WithContext(ctx).Model(&v1.%s{}).Count(&count).Error\n\treturn count, err\n}\n", m.name)
}

func emitUpsert(b *strings.Builder, m *modelSpec) {
	var conflict []string
	for _, pk := range m.pks {
		conflict = append(conflict, fmt.Sprintf("{Name: %q}", pk.column))
	}
	var updates []string
	for _, f := range m.fields {
		if f.skip || f.relation || f.pk || f.autoCreate {
			continue
		}
		updates = append(updates, fmt.Sprintf("%q", f.column))
	}
	fmt.Fprintf(b, "\n// Inserts or refreshes one %s row\nfunc (s *Store) Upsert%s(ctx context.Context, row *v1.%s) error {\n", m.opts.Table, m.name, m.name)
	if uuidPK(m) {
		fmt.Fprintf(b, "\tif row.%s == \"\" {\n\t\trow.%s = uuid.New().String()\n\t}\n", m.pks[0].goName, m.pks[0].goName)
	}
	fmt.Fprintf(b, "\treturn s.db.WithContext(ctx).Omit(clause.Associations).Clauses(clause.OnConflict{\n\t\tColumns:   []clause.Column{%s},\n\t\tDoUpdates: clause.AssignmentColumns([]string{%s}),\n\t}).Create(row).Error\n}\n", strings.Join(conflict, ", "), strings.Join(updates, ", "))
}

// Emits one annotated query, reports time usage
func emitQuery(b *strings.Builder, m *modelSpec, q *optionsv1.DbQuery) bool {
	params := parseParams(q.Params)
	order := q.OrderBy
	if order == "" {
		order = m.opts.OrderBy
	}
	sig := sigOf(params)
	if sig != "" {
		sig = ", " + sig
	}

	switch q.Kind {
	case optionsv1.QueryKind_QUERY_KIND_GET:
		fmt.Fprintf(b, "\n// Loads one row from %s\nfunc (s *Store) %s(ctx context.Context%s) (*v1.%s, error) {\n", m.opts.Table, q.Name, sig, m.name)
		fmt.Fprintf(b, "\tvar row v1.%s\n", m.name)
		chain := "s.db.WithContext(ctx)"
		for _, p := range q.Preload {
			chain += fmt.Sprintf(".Preload(%q)", p)
		}
		fmt.Fprintf(b, "\tif err := %s.%s.First(&row).Error; err != nil {\n", chain, whereCall(q.Where, argsOf(params)))
		if q.NotFoundNil {
			b.WriteString("\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn nil, nil\n\t\t}\n")
		} else {
			fmt.Fprintf(b, "\t\tif errors.Is(err, gorm.ErrRecordNotFound) {\n\t\t\treturn nil, fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t\t}\n", humanName(m.name))
		}
		b.WriteString("\t\treturn nil, err\n\t}\n\treturn &row, nil\n}\n")

	case optionsv1.QueryKind_QUERY_KIND_LIST:
		ret := fmt.Sprintf("([]*v1.%s, error)", m.name)
		extra := ""
		if q.Paginate {
			ret = fmt.Sprintf("([]*v1.%s, int64, error)", m.name)
			extra = ", offset, limit int"
		} else if q.LimitArg {
			extra = ", limit int"
		}
		fmt.Fprintf(b, "\n// Lists rows from %s\nfunc (s *Store) %s(ctx context.Context%s%s) %s {\n", m.opts.Table, q.Name, sig, extra, ret)
		fail := "nil, err"
		if q.Paginate {
			fail = "nil, 0, err"
			fmt.Fprintf(b, "\tvar total int64\n\tcounter := s.db.WithContext(ctx).Model(&v1.%s{})\n", m.name)
			if q.Where != "" {
				fmt.Fprintf(b, "\tcounter = counter.%s\n", whereCall(q.Where, argsOf(params)))
			}
			b.WriteString("\tif err := counter.Count(&total).Error; err != nil {\n\t\treturn nil, 0, err\n\t}\n")
		}
		fmt.Fprintf(b, "\tvar rows []*v1.%s\n", m.name)
		b.WriteString("\tq := s.db.WithContext(ctx)\n")
		for _, p := range q.Preload {
			fmt.Fprintf(b, "\tq = q.Preload(%q)\n", p)
		}
		if q.Where != "" {
			fmt.Fprintf(b, "\tq = q.%s\n", whereCall(q.Where, argsOf(params)))
		}
		if order != "" {
			fmt.Fprintf(b, "\tq = q.Order(%q)\n", order)
		}
		if q.Paginate {
			b.WriteString("\tq = q.Offset(offset)\n\tif limit > 0 {\n\t\tq = q.Limit(limit)\n\t}\n")
		} else if q.LimitArg {
			b.WriteString("\tif limit > 0 {\n\t\tq = q.Limit(limit)\n\t}\n")
		} else if q.Limit > 0 {
			fmt.Fprintf(b, "\tq = q.Limit(%d)\n", q.Limit)
		}
		fmt.Fprintf(b, "\tif err := q.Find(&rows).Error; err != nil {\n\t\treturn %s\n\t}\n", fail)
		if q.Paginate {
			b.WriteString("\treturn rows, total, nil\n}\n")
		} else {
			b.WriteString("\treturn rows, nil\n}\n")
		}

	case optionsv1.QueryKind_QUERY_KIND_DELETE:
		fmt.Fprintf(b, "\n// Deletes rows from %s\nfunc (s *Store) %s(ctx context.Context%s) error {\n", m.opts.Table, q.Name, sig)
		fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).%s.Delete(&v1.%s{})\n", whereCall(q.Where, argsOf(params)), m.name)
		b.WriteString("\tif res.Error != nil {\n\t\treturn res.Error\n\t}\n")
		if q.RequireRow {
			fmt.Fprintf(b, "\tif res.RowsAffected == 0 {\n\t\treturn fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t}\n", humanName(m.name))
		}
		b.WriteString("\treturn nil\n}\n")

	case optionsv1.QueryKind_QUERY_KIND_EXISTS:
		fmt.Fprintf(b, "\n// Reports whether a matching %s row exists\nfunc (s *Store) %s(ctx context.Context%s) (bool, error) {\n", m.opts.Table, q.Name, sig)
		fmt.Fprintf(b, "\tvar count int64\n\terr := s.db.WithContext(ctx).Model(&v1.%s{}).%s.Count(&count).Error\n\treturn count > 0, err\n}\n", m.name, whereCall(q.Where, argsOf(params)))

	case optionsv1.QueryKind_QUERY_KIND_COUNT:
		fmt.Fprintf(b, "\n// Counts matching rows in %s\nfunc (s *Store) %s(ctx context.Context%s) (int64, error) {\n", m.opts.Table, q.Name, sig)
		fmt.Fprintf(b, "\tvar count int64\n\terr := s.db.WithContext(ctx).Model(&v1.%s{}).%s.Count(&count).Error\n\treturn count, err\n}\n", m.name, whereCall(q.Where, argsOf(params)))

	case optionsv1.QueryKind_QUERY_KIND_UPDATE:
		fmt.Fprintf(b, "\n// Patches matching rows in %s\nfunc (s *Store) %s(ctx context.Context%s) error {\n", m.opts.Table, q.Name, sig)
		stmt := fmt.Sprintf("UPDATE %s SET %s WHERE %s", m.opts.Table, q.Set, q.Where)
		if len(params) == 0 {
			fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).Exec(%q)\n", stmt)
		} else {
			fmt.Fprintf(b, "\tres := s.db.WithContext(ctx).Exec(%q, %s)\n", stmt, argsOf(params))
		}
		b.WriteString("\tif res.Error != nil {\n\t\treturn res.Error\n\t}\n")
		if q.RequireRow {
			fmt.Fprintf(b, "\tif res.RowsAffected == 0 {\n\t\treturn fmt.Errorf(\"%s not found: %%w\", gorm.ErrRecordNotFound)\n\t}\n", humanName(m.name))
		}
		b.WriteString("\treturn nil\n}\n")

	default:
		fatal("query %s on %s has no kind", q.Name, m.name)
	}
	return usesTime(params)
}

// Go field name for a column on this model
func goFieldFor(m *modelSpec, column string) string {
	for _, f := range m.fields {
		if f.column == column {
			return f.goName
		}
	}
	fatal("model %s has no column %s", m.name, column)
	return ""
}

// Where invocation with optional bound args
func whereCall(where string, args string) string {
	if args == "" {
		return fmt.Sprintf("Where(%q)", where)
	}
	return fmt.Sprintf("Where(%q, %s)", where, args)
}
