// Emits model support code into the generated package
package main

import (
	"fmt"
	"go/format"
	"strings"
)

// Renders gorm.gen.go with hooks and the model registry
func renderSupport(models []*modelSpec) []byte {
	var b strings.Builder
	b.WriteString(`// Code generated by gormgen. DO NOT EDIT.

package discopanelv1

import (
	"context"
	"fmt"
	"reflect"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
	"gorm.io/gorm"
	"gorm.io/gorm/schema"
)

func init() {
	schema.RegisterSerializer("tspb", TimestampSerializer{})
}

// Stores protobuf timestamps as sqlite datetime values
type TimestampSerializer struct{}

// Reads a datetime column into a protobuf timestamp
func (TimestampSerializer) Scan(ctx context.Context, field *schema.Field, dst reflect.Value, dbValue any) error {
	if dbValue == nil {
		field.ReflectValueOf(ctx, dst).Set(reflect.Zero(field.FieldType))
		return nil
	}
	var t time.Time
	switch v := dbValue.(type) {
	case time.Time:
		t = v
	case string:
		parsed, err := parseDBTime(v)
		if err != nil {
			return err
		}
		t = parsed
	case []byte:
		parsed, err := parseDBTime(string(v))
		if err != nil {
			return err
		}
		t = parsed
	case int64:
		t = time.Unix(v, 0)
	default:
		return fmt.Errorf("tspb: unsupported db value %T", dbValue)
	}
	if t.IsZero() {
		field.ReflectValueOf(ctx, dst).Set(reflect.Zero(field.FieldType))
		return nil
	}
	field.ReflectValueOf(ctx, dst).Set(reflect.ValueOf(timestamppb.New(t)))
	return nil
}

// Writes a protobuf timestamp as a database time value
func (TimestampSerializer) Value(ctx context.Context, field *schema.Field, dst reflect.Value, fieldValue any) (any, error) {
	ts, ok := fieldValue.(*timestamppb.Timestamp)
	if !ok || ts == nil {
		return nil, nil
	}
	return ts.AsTime(), nil
}

// Accepts the datetime layouts sqlite drivers emit
func parseDBTime(s string) (time.Time, error) {
	layouts := []string{
		"2006-01-02 15:04:05.999999999-07:00",
		"2006-01-02 15:04:05.999999999",
		time.RFC3339Nano,
		"2006-01-02 15:04:05",
		"2006-01-02T15:04:05.999999999",
	}
	var last error
	for _, layout := range layouts {
		t, err := time.Parse(layout, s)
		if err == nil {
			return t, nil
		}
		last = err
	}
	return time.Time{}, fmt.Errorf("tspb: cannot parse %q: %w", s, last)
}

`)

	for _, m := range models {
		b.WriteString(fmt.Sprintf("func (*%s) TableName() string { return %q }\n\n", m.name, m.opts.Table))

		if m.created != "" {
			b.WriteString(fmt.Sprintf("func (x *%s) BeforeCreate(*gorm.DB) error {\n", m.name))
			b.WriteString(fmt.Sprintf("\tif x.%s == nil {\n\t\tx.%s = timestamppb.Now()\n\t}\n\treturn nil\n}\n\n", m.created, m.created))
		}
		if m.updated != "" {
			b.WriteString(fmt.Sprintf("func (x *%s) BeforeSave(*gorm.DB) error {\n", m.name))
			b.WriteString(fmt.Sprintf("\tx.%s = timestamppb.Now()\n\treturn nil\n}\n\n", m.updated))
		}
		if len(m.redacts) > 0 {
			b.WriteString(fmt.Sprintf("// Clears secret fields before the message leaves the panel\nfunc (x *%s) Redact() *%s {\n\tif x == nil {\n\t\treturn nil\n\t}\n", m.name, m.name))
			for _, r := range m.redacts {
				b.WriteString(fmt.Sprintf("\tx.%s = \"\"\n", r))
			}
			b.WriteString("\treturn x\n}\n\n")
		}
	}

	b.WriteString("// Every table for automigrate\nfunc AllModels() []any {\n\treturn []any{\n")
	for _, m := range models {
		b.WriteString(fmt.Sprintf("\t\t&%s{},\n", m.name))
	}
	b.WriteString("\t}\n}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		fatal("format support: %v\n%s", err, b.String())
	}
	return formatted
}
