// Code generated by gormgen. DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	v1 "github.com/nickheyer/discopanel/pkg/proto/discopanel/v1"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// Inserts rows into api_tokens
func (s *Store) CreateApiToken(ctx context.Context, rows ...*v1.ApiToken) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from api_tokens
func (s *Store) GetApiToken(ctx context.Context, id string) (*v1.ApiToken, error) {
	var row v1.ApiToken
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("api token not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from api_tokens
func (s *Store) ListApiTokens(ctx context.Context) ([]*v1.ApiToken, error) {
	var rows []*v1.ApiToken
	if err := s.db.WithContext(ctx).Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into api_tokens
func (s *Store) UpdateApiToken(ctx context.Context, row *v1.ApiToken) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one api_tokens row
func (s *Store) UpdateApiTokenFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ApiToken{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("api token not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from api_tokens
func (s *Store) DeleteApiToken(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.ApiToken{}, "id = ?", id).Error
}

// Counts rows in api_tokens
func (s *Store) CountApiTokens(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ApiToken{}).Count(&count).Error
	return count, err
}

// Loads one row from api_tokens
func (s *Store) GetApiTokenByHash(ctx context.Context, hash string) (*v1.ApiToken, error) {
	var row v1.ApiToken
	if err := s.db.WithContext(ctx).Where("token_hash = ?", hash).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("api token not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from api_tokens
func (s *Store) ListApiTokensByUser(ctx context.Context, userID string) ([]*v1.ApiToken, error) {
	var rows []*v1.ApiToken
	q := s.db.WithContext(ctx)
	q = q.Where("user_id = ? AND (is_module_token = false OR is_module_token IS NULL)", userID)
	q = q.Order("created_at DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Deletes rows from api_tokens
func (s *Store) DeleteUserApiToken(ctx context.Context, id string, userID string) error {
	res := s.db.WithContext(ctx).Where("id = ? AND user_id = ?", id, userID).Delete(&v1.ApiToken{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("api token not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Patches matching rows in api_tokens
func (s *Store) UpdateApiTokenLastUsed(ctx context.Context, t time.Time, id string) error {
	res := s.db.WithContext(ctx).Exec("UPDATE api_tokens SET last_used_at = ? WHERE id = ?", t, id)
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Inserts rows into finding_dismissals
func (s *Store) CreateFindingDismissal(ctx context.Context, rows ...*v1.FindingDismissal) error {
	if len(rows) == 0 {
		return nil
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from finding_dismissals
func (s *Store) GetFindingDismissal(ctx context.Context, serverID string, findingID string) (*v1.FindingDismissal, error) {
	var row v1.FindingDismissal
	if err := s.db.WithContext(ctx).First(&row, "server_id = ? AND finding_id = ?", serverID, findingID).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("finding dismissal not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from finding_dismissals
func (s *Store) ListFindingDismissals(ctx context.Context) ([]*v1.FindingDismissal, error) {
	var rows []*v1.FindingDismissal
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into finding_dismissals
func (s *Store) UpdateFindingDismissal(ctx context.Context, row *v1.FindingDismissal) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one finding_dismissals row
func (s *Store) UpdateFindingDismissalFields(ctx context.Context, serverID string, findingID string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.FindingDismissal{}).Where("server_id = ? AND finding_id = ?", serverID, findingID).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("finding dismissal not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from finding_dismissals
func (s *Store) DeleteFindingDismissal(ctx context.Context, serverID string, findingID string) error {
	return s.db.WithContext(ctx).Delete(&v1.FindingDismissal{}, "server_id = ? AND finding_id = ?", serverID, findingID).Error
}

// Counts rows in finding_dismissals
func (s *Store) CountFindingDismissals(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.FindingDismissal{}).Count(&count).Error
	return count, err
}

// Inserts or refreshes one finding_dismissals row
func (s *Store) UpsertFindingDismissal(ctx context.Context, row *v1.FindingDismissal) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "server_id"}, {Name: "finding_id"}},
		DoUpdates: clause.AssignmentColumns([]string{"content_hash", "dismissed_at"}),
	}).Create(row).Error
}

// Lists rows from finding_dismissals
func (s *Store) GetFindingDismissals(ctx context.Context, serverID string) ([]*v1.FindingDismissal, error) {
	var rows []*v1.FindingDismissal
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ?", serverID)
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into indexed_modpack_files
func (s *Store) CreateIndexedModpackFile(ctx context.Context, rows ...*v1.IndexedModpackFile) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from indexed_modpack_files
func (s *Store) GetIndexedModpackFile(ctx context.Context, id string) (*v1.IndexedModpackFile, error) {
	var row v1.IndexedModpackFile
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("indexed modpack file not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from indexed_modpack_files
func (s *Store) ListIndexedModpackFiles(ctx context.Context) ([]*v1.IndexedModpackFile, error) {
	var rows []*v1.IndexedModpackFile
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into indexed_modpack_files
func (s *Store) UpdateIndexedModpackFile(ctx context.Context, row *v1.IndexedModpackFile) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one indexed_modpack_files row
func (s *Store) UpdateIndexedModpackFileFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.IndexedModpackFile{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("indexed modpack file not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from indexed_modpack_files
func (s *Store) DeleteIndexedModpackFile(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.IndexedModpackFile{}, "id = ?", id).Error
}

// Counts rows in indexed_modpack_files
func (s *Store) CountIndexedModpackFiles(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.IndexedModpackFile{}).Count(&count).Error
	return count, err
}

// Inserts or refreshes one indexed_modpack_files row
func (s *Store) UpsertIndexedModpackFile(ctx context.Context, row *v1.IndexedModpackFile) error {
	if row.Id == "" {
		row.Id = uuid.New().String()
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "id"}},
		DoUpdates: clause.AssignmentColumns([]string{"modpack_id", "display_name", "file_name", "file_date", "file_length", "release_type", "download_url", "game_versions", "mod_loader", "server_pack_file_id"}),
	}).Create(row).Error
}

// Lists rows from indexed_modpack_files
func (s *Store) GetIndexedModpackFiles(ctx context.Context, modpackID string) ([]*v1.IndexedModpackFile, error) {
	var rows []*v1.IndexedModpackFile
	q := s.db.WithContext(ctx)
	q = q.Where("modpack_id = ?", modpackID)
	q = q.Order("file_date DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into indexed_modpacks
func (s *Store) CreateIndexedModpack(ctx context.Context, rows ...*v1.IndexedModpack) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from indexed_modpacks
func (s *Store) GetIndexedModpack(ctx context.Context, id string) (*v1.IndexedModpack, error) {
	var row v1.IndexedModpack
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("indexed modpack not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Saves one row into indexed_modpacks
func (s *Store) UpdateIndexedModpack(ctx context.Context, row *v1.IndexedModpack) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one indexed_modpacks row
func (s *Store) UpdateIndexedModpackFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.IndexedModpack{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("indexed modpack not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from indexed_modpacks
func (s *Store) DeleteIndexedModpack(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Delete(&v1.IndexedModpackFile{}, "modpack_id = ?", id).Error; err != nil {
			return err
		}
		if err := tx.Delete(&v1.ModpackFavorite{}, "modpack_id = ?", id).Error; err != nil {
			return err
		}
		return tx.Delete(&v1.IndexedModpack{}, "id = ?", id).Error
	})
}

// Counts rows in indexed_modpacks
func (s *Store) CountIndexedModpacks(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.IndexedModpack{}).Count(&count).Error
	return count, err
}

// Inserts or refreshes one indexed_modpacks row
func (s *Store) UpsertIndexedModpack(ctx context.Context, row *v1.IndexedModpack) error {
	if row.Id == "" {
		row.Id = uuid.New().String()
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "id"}},
		DoUpdates: clause.AssignmentColumns([]string{"indexer_id", "indexer", "name", "slug", "summary", "description", "logo_url", "website_url", "download_count", "categories", "game_versions", "mod_loaders", "latest_file_id", "date_created", "date_modified", "date_released", "mc_version", "java_version", "docker_image", "recommended_ram", "updated_at"}),
	}).Create(row).Error
}

// Loads one row from indexed_modpacks
func (s *Store) GetModpackBySlug(ctx context.Context, slug string) (*v1.IndexedModpack, error) {
	var row v1.IndexedModpack
	if err := s.db.WithContext(ctx).Where("slug = ?", slug).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &row, nil
}

// Loads one row from indexed_modpacks
func (s *Store) GetModpackByWebsiteURL(ctx context.Context, url string) (*v1.IndexedModpack, error) {
	var row v1.IndexedModpack
	if err := s.db.WithContext(ctx).Where("website_url = ?", url).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from indexed_modpacks
func (s *Store) ListIndexedModpacks(ctx context.Context, offset, limit int) ([]*v1.IndexedModpack, int64, error) {
	var total int64
	counter := s.db.WithContext(ctx).Model(&v1.IndexedModpack{})
	if err := counter.Count(&total).Error; err != nil {
		return nil, 0, err
	}
	var rows []*v1.IndexedModpack
	q := s.db.WithContext(ctx)
	q = q.Order("download_count DESC")
	q = q.Offset(offset)
	if limit > 0 {
		q = q.Limit(limit)
	}
	if err := q.Find(&rows).Error; err != nil {
		return nil, 0, err
	}
	return rows, total, nil
}

// Inserts rows into metrics_samples
func (s *Store) CreateMetricsSample(ctx context.Context, rows ...*v1.MetricsSample) error {
	if len(rows) == 0 {
		return nil
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from metrics_samples
func (s *Store) GetMetricsSample(ctx context.Context, id int64) (*v1.MetricsSample, error) {
	var row v1.MetricsSample
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("metrics sample not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Deletes one row from metrics_samples
func (s *Store) DeleteMetricsSample(ctx context.Context, id int64) error {
	return s.db.WithContext(ctx).Delete(&v1.MetricsSample{}, "id = ?", id).Error
}

// Counts rows in metrics_samples
func (s *Store) CountMetricsSamples(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.MetricsSample{}).Count(&count).Error
	return count, err
}

// Deletes rows from metrics_samples
func (s *Store) PruneMetricsSamples(ctx context.Context, resolution int, olderThan time.Time) error {
	res := s.db.WithContext(ctx).Where("resolution = ? AND datetime(timestamp) < datetime(?)", resolution, olderThan).Delete(&v1.MetricsSample{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Inserts rows into modpack_favorites
func (s *Store) CreateModpackFavorite(ctx context.Context, rows ...*v1.ModpackFavorite) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from modpack_favorites
func (s *Store) GetModpackFavorite(ctx context.Context, id string) (*v1.ModpackFavorite, error) {
	var row v1.ModpackFavorite
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("modpack favorite not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from modpack_favorites
func (s *Store) ListModpackFavorites(ctx context.Context) ([]*v1.ModpackFavorite, error) {
	var rows []*v1.ModpackFavorite
	if err := s.db.WithContext(ctx).Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into modpack_favorites
func (s *Store) UpdateModpackFavorite(ctx context.Context, row *v1.ModpackFavorite) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one modpack_favorites row
func (s *Store) UpdateModpackFavoriteFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ModpackFavorite{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("modpack favorite not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from modpack_favorites
func (s *Store) DeleteModpackFavorite(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.ModpackFavorite{}, "id = ?", id).Error
}

// Counts rows in modpack_favorites
func (s *Store) CountModpackFavorites(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ModpackFavorite{}).Count(&count).Error
	return count, err
}

// Deletes rows from modpack_favorites
func (s *Store) RemoveModpackFavorite(ctx context.Context, modpackID string) error {
	res := s.db.WithContext(ctx).Where("modpack_id = ?", modpackID).Delete(&v1.ModpackFavorite{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Reports whether a matching modpack_favorites row exists
func (s *Store) IsModpackFavorited(ctx context.Context, modpackID string) (bool, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ModpackFavorite{}).Where("modpack_id = ?", modpackID).Count(&count).Error
	return count > 0, err
}

// Lists rows from modpack_favorites
func (s *Store) ListFavoriteModpacks(ctx context.Context) ([]*v1.ModpackFavorite, error) {
	var rows []*v1.ModpackFavorite
	q := s.db.WithContext(ctx)
	q = q.Preload("Modpack")
	q = q.Order("created_at DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into mods
func (s *Store) CreateMod(ctx context.Context, rows ...*v1.Mod) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from mods
func (s *Store) GetMod(ctx context.Context, id string) (*v1.Mod, error) {
	var row v1.Mod
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("mod not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from mods
func (s *Store) ListMods(ctx context.Context) ([]*v1.Mod, error) {
	var rows []*v1.Mod
	if err := s.db.WithContext(ctx).Order("name").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into mods
func (s *Store) UpdateMod(ctx context.Context, row *v1.Mod) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one mods row
func (s *Store) UpdateModFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.Mod{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("mod not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from mods
func (s *Store) DeleteMod(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.Mod{}, "id = ?", id).Error
}

// Counts rows in mods
func (s *Store) CountMods(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.Mod{}).Count(&count).Error
	return count, err
}

// Lists rows from mods
func (s *Store) ListServerMods(ctx context.Context, serverID string) ([]*v1.Mod, error) {
	var rows []*v1.Mod
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ?", serverID)
	q = q.Order("name")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into module_templates
func (s *Store) CreateModuleTemplate(ctx context.Context, rows ...*v1.ModuleTemplate) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from module_templates
func (s *Store) GetModuleTemplate(ctx context.Context, id string) (*v1.ModuleTemplate, error) {
	var row v1.ModuleTemplate
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("module template not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from module_templates
func (s *Store) ListModuleTemplates(ctx context.Context) ([]*v1.ModuleTemplate, error) {
	var rows []*v1.ModuleTemplate
	if err := s.db.WithContext(ctx).Order("type ASC, name ASC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into module_templates
func (s *Store) UpdateModuleTemplate(ctx context.Context, row *v1.ModuleTemplate) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one module_templates row
func (s *Store) UpdateModuleTemplateFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ModuleTemplate{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("module template not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from module_templates
func (s *Store) DeleteModuleTemplate(ctx context.Context, id string) error {
	var refsModule int64
	if err := s.db.WithContext(ctx).Model(&v1.Module{}).Where("template_id = ?", id).Count(&refsModule).Error; err != nil {
		return err
	}
	if refsModule > 0 {
		return fmt.Errorf("module template still referenced by %d module rows", refsModule)
	}
	return s.db.WithContext(ctx).Delete(&v1.ModuleTemplate{}, "id = ?", id).Error
}

// Counts rows in module_templates
func (s *Store) CountModuleTemplates(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ModuleTemplate{}).Count(&count).Error
	return count, err
}

// Loads one row from module_templates
func (s *Store) GetModuleTemplateByName(ctx context.Context, name string) (*v1.ModuleTemplate, error) {
	var row v1.ModuleTemplate
	if err := s.db.WithContext(ctx).Where("name = ?", name).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("module template not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from module_templates
func (s *Store) ListModuleTemplatesByType(ctx context.Context, t v1.ModuleTemplateType) ([]*v1.ModuleTemplate, error) {
	var rows []*v1.ModuleTemplate
	q := s.db.WithContext(ctx)
	q = q.Where("type = ?", t)
	q = q.Order("name ASC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into modules
func (s *Store) CreateModule(ctx context.Context, rows ...*v1.Module) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from modules
func (s *Store) GetModule(ctx context.Context, id string) (*v1.Module, error) {
	var row v1.Module
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("module not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from modules
func (s *Store) ListModules(ctx context.Context) ([]*v1.Module, error) {
	var rows []*v1.Module
	if err := s.db.WithContext(ctx).Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into modules
func (s *Store) UpdateModule(ctx context.Context, row *v1.Module) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one modules row
func (s *Store) UpdateModuleFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.Module{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("module not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from modules
func (s *Store) DeleteModule(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.Module{}, "id = ?", id).Error
}

// Counts rows in modules
func (s *Store) CountModules(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.Module{}).Count(&count).Error
	return count, err
}

// Lists rows from modules
func (s *Store) ListServerModules(ctx context.Context, serverID string) ([]*v1.Module, error) {
	var rows []*v1.Module
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ?", serverID)
	q = q.Order("name ASC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Lists rows from modules
func (s *Store) ListModulesByTemplate(ctx context.Context, templateID string) ([]*v1.Module, error) {
	var rows []*v1.Module
	q := s.db.WithContext(ctx)
	q = q.Where("template_id = ?", templateID)
	q = q.Order("created_at DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Loads one row from modules
func (s *Store) GetModuleByContainerID(ctx context.Context, containerID string) (*v1.Module, error) {
	var row v1.Module
	if err := s.db.WithContext(ctx).Where("container_id = ? AND container_id != ''", containerID).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from modules
func (s *Store) ListAutoStartModules(ctx context.Context) ([]*v1.Module, error) {
	var rows []*v1.Module
	q := s.db.WithContext(ctx)
	q = q.Where("auto_start = true AND detached = false")
	q = q.Order("created_at DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Lists rows from modules
func (s *Store) ListModulesFollowingServerLifecycle(ctx context.Context, serverID string) ([]*v1.Module, error) {
	var rows []*v1.Module
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ? AND follow_server_lifecycle = true", serverID)
	q = q.Order("created_at DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into proxy_configs
func (s *Store) CreateProxyConfig(ctx context.Context, rows ...*v1.ProxyConfig) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Lists rows from proxy_configs
func (s *Store) ListProxyConfigs(ctx context.Context) ([]*v1.ProxyConfig, error) {
	var rows []*v1.ProxyConfig
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into proxy_configs
func (s *Store) UpdateProxyConfig(ctx context.Context, row *v1.ProxyConfig) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one proxy_configs row
func (s *Store) UpdateProxyConfigFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ProxyConfig{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("proxy config not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from proxy_configs
func (s *Store) DeleteProxyConfig(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.ProxyConfig{}, "id = ?", id).Error
}

// Counts rows in proxy_configs
func (s *Store) CountProxyConfigs(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ProxyConfig{}).Count(&count).Error
	return count, err
}

// Inserts rows into proxy_listeners
func (s *Store) CreateProxyListener(ctx context.Context, rows ...*v1.ProxyListener) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from proxy_listeners
func (s *Store) GetProxyListener(ctx context.Context, id string) (*v1.ProxyListener, error) {
	var row v1.ProxyListener
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("proxy listener not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from proxy_listeners
func (s *Store) ListProxyListeners(ctx context.Context) ([]*v1.ProxyListener, error) {
	var rows []*v1.ProxyListener
	if err := s.db.WithContext(ctx).Order("is_default DESC, port ASC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into proxy_listeners
func (s *Store) UpdateProxyListener(ctx context.Context, row *v1.ProxyListener) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one proxy_listeners row
func (s *Store) UpdateProxyListenerFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ProxyListener{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("proxy listener not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from proxy_listeners
func (s *Store) DeleteProxyListener(ctx context.Context, id string) error {
	var refsServer int64
	if err := s.db.WithContext(ctx).Model(&v1.Server{}).Where("proxy_listener_id = ?", id).Count(&refsServer).Error; err != nil {
		return err
	}
	if refsServer > 0 {
		return fmt.Errorf("proxy listener still referenced by %d server rows", refsServer)
	}
	return s.db.WithContext(ctx).Delete(&v1.ProxyListener{}, "id = ?", id).Error
}

// Counts rows in proxy_listeners
func (s *Store) CountProxyListeners(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ProxyListener{}).Count(&count).Error
	return count, err
}

// Loads one row from proxy_listeners
func (s *Store) GetProxyListenerByPort(ctx context.Context, port int) (*v1.ProxyListener, error) {
	var row v1.ProxyListener
	if err := s.db.WithContext(ctx).Where("port = ?", port).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("proxy listener not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Inserts rows into registration_invites
func (s *Store) CreateRegistrationInvite(ctx context.Context, rows ...*v1.RegistrationInvite) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from registration_invites
func (s *Store) GetRegistrationInvite(ctx context.Context, id string) (*v1.RegistrationInvite, error) {
	var row v1.RegistrationInvite
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("registration invite not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from registration_invites
func (s *Store) ListRegistrationInvites(ctx context.Context) ([]*v1.RegistrationInvite, error) {
	var rows []*v1.RegistrationInvite
	if err := s.db.WithContext(ctx).Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into registration_invites
func (s *Store) UpdateRegistrationInvite(ctx context.Context, row *v1.RegistrationInvite) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one registration_invites row
func (s *Store) UpdateRegistrationInviteFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.RegistrationInvite{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("registration invite not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from registration_invites
func (s *Store) DeleteRegistrationInvite(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.RegistrationInvite{}, "id = ?", id).Error
}

// Counts rows in registration_invites
func (s *Store) CountRegistrationInvites(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.RegistrationInvite{}).Count(&count).Error
	return count, err
}

// Loads one row from registration_invites
func (s *Store) GetRegistrationInviteByCode(ctx context.Context, code string) (*v1.RegistrationInvite, error) {
	var row v1.RegistrationInvite
	if err := s.db.WithContext(ctx).Where("code = ?", code).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("registration invite not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Patches matching rows in registration_invites
func (s *Store) IncrementInviteUseCount(ctx context.Context, id string) error {
	res := s.db.WithContext(ctx).Exec("UPDATE registration_invites SET use_count = use_count + 1 WHERE id = ?", id)
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Inserts rows into roles
func (s *Store) CreateRole(ctx context.Context, rows ...*v1.Role) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from roles
func (s *Store) GetRole(ctx context.Context, id string) (*v1.Role, error) {
	var row v1.Role
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("role not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from roles
func (s *Store) ListRoles(ctx context.Context) ([]*v1.Role, error) {
	var rows []*v1.Role
	if err := s.db.WithContext(ctx).Order("is_system DESC, name ASC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into roles
func (s *Store) UpdateRole(ctx context.Context, row *v1.Role) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one roles row
func (s *Store) UpdateRoleFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.Role{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("role not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Counts rows in roles
func (s *Store) CountRoles(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.Role{}).Count(&count).Error
	return count, err
}

// Lists rows from roles
func (s *Store) GetDefaultRoles(ctx context.Context) ([]*v1.Role, error) {
	var rows []*v1.Role
	q := s.db.WithContext(ctx)
	q = q.Where("is_default = true")
	q = q.Order("is_system DESC, name ASC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Loads one row from roles
func (s *Store) GetRoleByName(ctx context.Context, name string) (*v1.Role, error) {
	var row v1.Role
	if err := s.db.WithContext(ctx).Where("name = ?", name).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("role not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Inserts rows into scheduled_tasks
func (s *Store) CreateScheduledTask(ctx context.Context, rows ...*v1.ScheduledTask) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from scheduled_tasks
func (s *Store) GetScheduledTask(ctx context.Context, id string) (*v1.ScheduledTask, error) {
	var row v1.ScheduledTask
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("scheduled task not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from scheduled_tasks
func (s *Store) ListScheduledTasks(ctx context.Context) ([]*v1.ScheduledTask, error) {
	var rows []*v1.ScheduledTask
	if err := s.db.WithContext(ctx).Order("datetime(next_run) ASC NULLS LAST").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into scheduled_tasks
func (s *Store) UpdateScheduledTask(ctx context.Context, row *v1.ScheduledTask) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one scheduled_tasks row
func (s *Store) UpdateScheduledTaskFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ScheduledTask{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("scheduled task not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from scheduled_tasks
func (s *Store) DeleteScheduledTask(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Delete(&v1.TaskExecution{}, "task_id = ?", id).Error; err != nil {
			return err
		}
		return tx.Delete(&v1.ScheduledTask{}, "id = ?", id).Error
	})
}

// Counts rows in scheduled_tasks
func (s *Store) CountScheduledTasks(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ScheduledTask{}).Count(&count).Error
	return count, err
}

// Lists rows from scheduled_tasks
func (s *Store) ListServerScheduledTasks(ctx context.Context, serverID string) ([]*v1.ScheduledTask, error) {
	var rows []*v1.ScheduledTask
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ?", serverID)
	q = q.Order("created_at DESC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Lists rows from scheduled_tasks
func (s *Store) ListDueScheduledTasks(ctx context.Context, status v1.TaskStatus, before time.Time) ([]*v1.ScheduledTask, error) {
	var rows []*v1.ScheduledTask
	q := s.db.WithContext(ctx)
	q = q.Where("status = ? AND next_run IS NOT NULL AND datetime(next_run) <= datetime(?)", status, before)
	q = q.Order("datetime(next_run) ASC")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Lists rows from scheduled_tasks
func (s *Store) ListEventScheduledTasks(ctx context.Context, serverID string, status v1.TaskStatus, schedule v1.ScheduleType) ([]*v1.ScheduledTask, error) {
	var rows []*v1.ScheduledTask
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ? AND status = ? AND schedule = ?", serverID, status, schedule)
	q = q.Order("datetime(next_run) ASC NULLS LAST")
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into server_actions
func (s *Store) CreateServerAction(ctx context.Context, rows ...*v1.ServerAction) error {
	if len(rows) == 0 {
		return nil
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from server_actions
func (s *Store) GetServerAction(ctx context.Context, id int64) (*v1.ServerAction, error) {
	var row v1.ServerAction
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("server action not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Saves one row into server_actions
func (s *Store) UpdateServerAction(ctx context.Context, row *v1.ServerAction) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one server_actions row
func (s *Store) UpdateServerActionFields(ctx context.Context, id int64, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ServerAction{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("server action not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from server_actions
func (s *Store) DeleteServerAction(ctx context.Context, id int64) error {
	return s.db.WithContext(ctx).Delete(&v1.ServerAction{}, "id = ?", id).Error
}

// Counts rows in server_actions
func (s *Store) CountServerActions(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ServerAction{}).Count(&count).Error
	return count, err
}

// Inserts rows into server_properties
func (s *Store) CreateServerProperties(ctx context.Context, rows ...*v1.ServerProperties) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Lists rows from server_properties
func (s *Store) ListServerProperties(ctx context.Context) ([]*v1.ServerProperties, error) {
	var rows []*v1.ServerProperties
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into server_properties
func (s *Store) UpdateServerProperties(ctx context.Context, row *v1.ServerProperties) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one server_properties row
func (s *Store) UpdateServerPropertiesFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.ServerProperties{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("server properties not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from server_properties
func (s *Store) DeleteServerProperties(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.ServerProperties{}, "id = ?", id).Error
}

// Counts rows in server_properties
func (s *Store) CountServerProperties(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.ServerProperties{}).Count(&count).Error
	return count, err
}

// Loads one row from server_properties
func (s *Store) GetServerProperties(ctx context.Context, serverID string) (*v1.ServerProperties, error) {
	var row v1.ServerProperties
	if err := s.db.WithContext(ctx).Where("server_id = ?", serverID).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("server properties not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Loads one row from servers
func (s *Store) GetServer(ctx context.Context, id string) (*v1.Server, error) {
	var row v1.Server
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("server not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from servers
func (s *Store) ListServers(ctx context.Context) ([]*v1.Server, error) {
	var rows []*v1.Server
	if err := s.db.WithContext(ctx).Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Patches columns on one servers row
func (s *Store) UpdateServerFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.Server{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("server not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Counts rows in servers
func (s *Store) CountServers(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.Server{}).Count(&count).Error
	return count, err
}

// Loads one row from servers
func (s *Store) GetServerByAgentTokenHash(ctx context.Context, hash string) (*v1.Server, error) {
	var row v1.Server
	if err := s.db.WithContext(ctx).Where("agent_token_hash = ? AND agent_token_hash != ''", hash).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("server not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Loads one row from servers
func (s *Store) GetServerByPort(ctx context.Context, port int) (*v1.Server, error) {
	var row v1.Server
	if err := s.db.WithContext(ctx).Where("port = ? AND (proxy_hostname IS NULL OR proxy_hostname = '')", port).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &row, nil
}

// Inserts rows into sessions
func (s *Store) CreateSession(ctx context.Context, rows ...*v1.Session) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Lists rows from sessions
func (s *Store) ListSessions(ctx context.Context) ([]*v1.Session, error) {
	var rows []*v1.Session
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into sessions
func (s *Store) UpdateSession(ctx context.Context, row *v1.Session) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one sessions row
func (s *Store) UpdateSessionFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.Session{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("session not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Counts rows in sessions
func (s *Store) CountSessions(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.Session{}).Count(&count).Error
	return count, err
}

// Loads one row from sessions
func (s *Store) GetSession(ctx context.Context, token string, now time.Time) (*v1.Session, error) {
	var row v1.Session
	if err := s.db.WithContext(ctx).Preload("User").Where("token = ? AND datetime(expires_at) > datetime(?)", token, now).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("session not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Deletes rows from sessions
func (s *Store) DeleteSession(ctx context.Context, token string) error {
	res := s.db.WithContext(ctx).Where("token = ?", token).Delete(&v1.Session{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Deletes rows from sessions
func (s *Store) CleanExpiredSessions(ctx context.Context, now time.Time) error {
	res := s.db.WithContext(ctx).Where("datetime(expires_at) < datetime(?)", now).Delete(&v1.Session{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Deletes rows from sessions
func (s *Store) CleanAllSessions(ctx context.Context) error {
	res := s.db.WithContext(ctx).Where("1 = 1").Delete(&v1.Session{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Inserts rows into system_settings
func (s *Store) CreateSystemSetting(ctx context.Context, rows ...*v1.SystemSetting) error {
	if len(rows) == 0 {
		return nil
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from system_settings
func (s *Store) GetSystemSetting(ctx context.Context, key string) (*v1.SystemSetting, error) {
	var row v1.SystemSetting
	if err := s.db.WithContext(ctx).First(&row, "key = ?", key).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("system setting not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from system_settings
func (s *Store) ListSystemSettings(ctx context.Context) ([]*v1.SystemSetting, error) {
	var rows []*v1.SystemSetting
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into system_settings
func (s *Store) UpdateSystemSetting(ctx context.Context, row *v1.SystemSetting) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one system_settings row
func (s *Store) UpdateSystemSettingFields(ctx context.Context, key string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.SystemSetting{}).Where("key = ?", key).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("system setting not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from system_settings
func (s *Store) DeleteSystemSetting(ctx context.Context, key string) error {
	return s.db.WithContext(ctx).Delete(&v1.SystemSetting{}, "key = ?", key).Error
}

// Counts rows in system_settings
func (s *Store) CountSystemSettings(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.SystemSetting{}).Count(&count).Error
	return count, err
}

// Inserts rows into task_executions
func (s *Store) CreateTaskExecution(ctx context.Context, rows ...*v1.TaskExecution) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from task_executions
func (s *Store) GetTaskExecution(ctx context.Context, id string) (*v1.TaskExecution, error) {
	var row v1.TaskExecution
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("task execution not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Saves one row into task_executions
func (s *Store) UpdateTaskExecution(ctx context.Context, row *v1.TaskExecution) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one task_executions row
func (s *Store) UpdateTaskExecutionFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.TaskExecution{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("task execution not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from task_executions
func (s *Store) DeleteTaskExecution(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.TaskExecution{}, "id = ?", id).Error
}

// Counts rows in task_executions
func (s *Store) CountTaskExecutions(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.TaskExecution{}).Count(&count).Error
	return count, err
}

// Lists rows from task_executions
func (s *Store) ListTaskExecutions(ctx context.Context, taskID string, limit int) ([]*v1.TaskExecution, error) {
	var rows []*v1.TaskExecution
	q := s.db.WithContext(ctx)
	q = q.Where("task_id = ?", taskID)
	q = q.Order("started_at DESC")
	if limit > 0 {
		q = q.Limit(limit)
	}
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Lists rows from task_executions
func (s *Store) ListServerTaskExecutions(ctx context.Context, serverID string, limit int) ([]*v1.TaskExecution, error) {
	var rows []*v1.TaskExecution
	q := s.db.WithContext(ctx)
	q = q.Where("server_id = ?", serverID)
	q = q.Order("started_at DESC")
	if limit > 0 {
		q = q.Limit(limit)
	}
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Deletes rows from task_executions
func (s *Store) DeleteTaskExecutions(ctx context.Context, taskID string) error {
	res := s.db.WithContext(ctx).Where("task_id = ?", taskID).Delete(&v1.TaskExecution{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Inserts rows into user_roles
func (s *Store) CreateUserRole(ctx context.Context, rows ...*v1.UserRole) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from user_roles
func (s *Store) GetUserRole(ctx context.Context, id string) (*v1.UserRole, error) {
	var row v1.UserRole
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("user role not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from user_roles
func (s *Store) ListUserRoles(ctx context.Context) ([]*v1.UserRole, error) {
	var rows []*v1.UserRole
	if err := s.db.WithContext(ctx).Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into user_roles
func (s *Store) UpdateUserRole(ctx context.Context, row *v1.UserRole) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one user_roles row
func (s *Store) UpdateUserRoleFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.UserRole{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("user role not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from user_roles
func (s *Store) DeleteUserRole(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Delete(&v1.UserRole{}, "id = ?", id).Error
}

// Counts rows in user_roles
func (s *Store) CountUserRoles(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.UserRole{}).Count(&count).Error
	return count, err
}

// Deletes rows from user_roles
func (s *Store) UnassignRole(ctx context.Context, userID string, roleName string) error {
	res := s.db.WithContext(ctx).Where("user_id = ? AND role_name = ?", userID, roleName).Delete(&v1.UserRole{})
	if res.Error != nil {
		return res.Error
	}
	return nil
}

// Loads one row from user_roles
func (s *Store) GetUserRoleAssignment(ctx context.Context, userID string, roleName string) (*v1.UserRole, error) {
	var row v1.UserRole
	if err := s.db.WithContext(ctx).Where("user_id = ? AND role_name = ?", userID, roleName).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from user_roles
func (s *Store) ListUserRolesByUser(ctx context.Context, userID string) ([]*v1.UserRole, error) {
	var rows []*v1.UserRole
	q := s.db.WithContext(ctx)
	q = q.Where("user_id = ?", userID)
	if err := q.Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Inserts rows into users
func (s *Store) CreateUser(ctx context.Context, rows ...*v1.User) error {
	if len(rows) == 0 {
		return nil
	}
	for _, r := range rows {
		if r.Id == "" {
			r.Id = uuid.New().String()
		}
	}
	return s.db.WithContext(ctx).Omit(clause.Associations).Create(rows).Error
}

// Loads one row from users
func (s *Store) GetUser(ctx context.Context, id string) (*v1.User, error) {
	var row v1.User
	if err := s.db.WithContext(ctx).First(&row, "id = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("user not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Lists rows from users
func (s *Store) ListUsers(ctx context.Context) ([]*v1.User, error) {
	var rows []*v1.User
	if err := s.db.WithContext(ctx).Order("created_at DESC").Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// Saves one row into users
func (s *Store) UpdateUser(ctx context.Context, row *v1.User) error {
	return s.db.WithContext(ctx).Omit(clause.Associations).Save(row).Error
}

// Patches columns on one users row
func (s *Store) UpdateUserFields(ctx context.Context, id string, fields map[string]any) error {
	if len(fields) == 0 {
		return nil
	}
	res := s.db.WithContext(ctx).Model(&v1.User{}).Where("id = ?", id).Updates(fields)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return fmt.Errorf("user not found: %w", gorm.ErrRecordNotFound)
	}
	return nil
}

// Deletes one row from users
func (s *Store) DeleteUser(ctx context.Context, id string) error {
	return s.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		if err := tx.Delete(&v1.Session{}, "user_id = ?", id).Error; err != nil {
			return err
		}
		if err := tx.Delete(&v1.ApiToken{}, "user_id = ?", id).Error; err != nil {
			return err
		}
		if err := tx.Delete(&v1.UserRole{}, "user_id = ?", id).Error; err != nil {
			return err
		}
		return tx.Delete(&v1.User{}, "id = ?", id).Error
	})
}

// Counts rows in users
func (s *Store) CountUsers(ctx context.Context) (int64, error) {
	var count int64
	err := s.db.WithContext(ctx).Model(&v1.User{}).Count(&count).Error
	return count, err
}

// Loads one row from users
func (s *Store) GetUserByUsernameAndProvider(ctx context.Context, username string, provider string) (*v1.User, error) {
	var row v1.User
	if err := s.db.WithContext(ctx).Where("username = ? AND auth_provider = ?", username, provider).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("user not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}

// Loads one row from users
func (s *Store) GetUserByOIDCSubject(ctx context.Context, subject string) (*v1.User, error) {
	var row v1.User
	if err := s.db.WithContext(ctx).Where("oidc_subject = ? AND oidc_subject != ''", subject).First(&row).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("user not found: %w", gorm.ErrRecordNotFound)
		}
		return nil, err
	}
	return &row, nil
}
